### PR TITLE
Add a few type classes to generated tuple instances

### PR DESCRIPTION
**Pull request by edmundnoble**

### CODE REVIEW

**Comment by peterneyens** [comment]
Should we add instances for `CommutativeSemigroup`, `CommutativeGroup` and `BoundedSemilattice` while we are at it?

**Comment by johnynek** [comment]
We're going to need generators for our generators.

Are we getting the priorities correct? We want `CommutativeX` to be a higher priority than `X`.

It would be interesting if we had some better way to generalize over this.

**Comment by johnynek** [comment]
I often wonder how long this approach is the right one and whether a shapeless based approach would be almost as fast and much cleaner to maintain.

**Comment by edmundnoble** [comment]
@johnynek What about Monoid and Semigroup for example, shouldn't they be different priorities too?

@peterneyens I added the two suggested as well.

Note this breaks bincompat, and so needs to be for 1.0.0.

**Comment by kailuowang** [comment]
If there is concerns over breaking bin comp for kernel we can add these instances in cats.core right?

**Comment by johnynek** [comment]
these are fine from algebird's point of view. We don't use these traits directly.

**Comment by johnynek** [comment]
@edmundnoble yes, I think the priority issue might also be a problem for Semigroup. I think it was an oversight. We should probably have resolution tests to make sure things work as expected. Just using Tuple2 is probably enough.

**Comment by kailuowang** [comment]
@edmundnoble I wonder if you have time to finish up this PR? Looks like we are close (1. fix the priority, and 2. add mima exception)

**Comment by kailuowang** [comment]
Continued in #1967

**Pull request closed without merging**
