### PR TITLE
Add TraverseM (Continuation of #1476)

### PR DESCRIPTION
**Pull request by LukaJCB**
Just merged this with Master for now. Not sure if we need other changes before merging. :)

### CODE REVIEW

**Comment by kailuowang** [comment]
also need mima exception

**Comment by johnynek** [comment]
So, I couldn’t get a test to pass before. It seems like a good idea, but I think even for List, which is an interesting Traverse case because it can eat very big, I didn’t get agreement.

There is also the naming concern. It is a bit junky to have traverse and traverseM. I may be in favor of punting this until we could find something similar to tailRecM for Applicative that would allow us to have stack safety for traverse.

**Comment by LukaJCB** [comment]
Maybe of interest: https://github.com/paf31/purescript-safely

**Comment by LukaJCB** [comment]
Going to close this for now :)

**Pull request closed without merging**
