### PR TITLE
improve EitherT inference for use in for-comprehension

### PR DESCRIPTION
**Pull request by jtjeferreira**

### CODE REVIEW

**Comment by kailuowang** [comment]
The original signature is to enable for comprehension for EitherT with different left type, see  https://github.com/typelevel/cats/pull/1506. We've been back and forth on this one. Should probably add a FAQ entry.

**Comment by jtjeferreira** [comment]
@kailuowang I asked first in https://gitter.im/typelevel/cats?at=58f8c38708c00c092a9bdb7c. Maybe a unit test would be enough...

**Comment by kailuowang** [comment]
@jtjeferreira to be clear I am 👎  on dropping support for for-comprehension with `EitherT` with different Left types. I think its benefit justifies the inconvenience of the imperfect type inference.

**Comment by jtjeferreira** [comment]
I understood. Was just suggesting that instead of adding something to the FAQ, just add that example from #1506 to a unit test. I can create a PR with that...

**Pull request closed without merging**
