### PR TITLE
Functor tupleLeft and tupleRight

### PR DESCRIPTION
**Pull request by edmundnoble**
`strengthL` and `strengthR` for `Functor`s. Tuple regular values with effectful ones.

### CODE REVIEW

**Comment by adelbertc** [comment]
👍

**Comment by peterneyens** [comment]
I have been thinking about adding these myself, but I wonder if we can't come up with some easier names (even though that's what they are called in scalaz and there seems to be a `strength` function in Haskell as well). Maybe something like `tupleLeft` / `tupleRight` ?

If nobody shares my concern, I am fine adding these as they stand.

**Comment by edmundnoble** [comment]
@peterneyens I am inclined to agree, but I don't at all feel strongly.

**Comment by johnynek** [comment]
.tuple for F[A], B to F[(A, B)] and .tupleSwap for the the other variant
would be my naming instinct, but I like non-insider names geared at
discoverability and and ease of remembering.

**Comment by adelbertc** [comment]
Since we have `Cartesian#product` maybe `productLeft` and `productRight` ?

**Comment by edmundnoble** [comment]
I've switched it around to `tupleLeft` and `tupleRight`, just because I don't think presuming an order of tupling is intuitive @johnynek and I don't want to confuse this with `Cartesian` ops because this requires `Functor` @adelbertc. I hope this is agreeable.

**Comment by johnynek** [comment]
👍

**Pull request merged**
