### PR TITLE
We should start publishing to org.typelevel.

### PR DESCRIPTION
**Pull request by non**
Note that after we do a new release to this new organization,
we'll need to update two files:

 * README.md - update information about finding the release
 * docs/src/site/index.md - same idea

### CODE REVIEW

**Comment by ceedubs** [comment]
:+1:

**Comment by adelbertc** [comment]
:+1: on green

**Comment by ceedubs** [comment]
This resolves #723

**Comment by striation** [comment]
Moving the repo borked Travis apparently.

**Comment by non** [comment]
OK, just restarted Travis. Apparently moving the repo while Travis is running causes problems.

**Pull request merged**
