### PR TITLE
adding override modifier

### PR DESCRIPTION
**Pull request by gokyo**
Thank you for contributing to Cats!

This is a kind reminder to run `sbt +prePR` and commit the changed files, if any, before submitting.

### CODE REVIEW

**Review by rossabaker — COMMENTED** [review]
Thanks, @gokyo.  Is this just a style thing, or did it fix a specific problem?

**Comment by gokyo** [comment]
@rossabaker 
It is not an issue. 
The code would behave in the same way, regardless if you use or not the `override` modifier. 
I find the code easier to read when the overridden methods have the `override` modifier. 
I wonder what your views are.

**Comment by ritschwumm** [comment]
i wouldn't put an `override` here: it's abstract in Semigroup, so imho it's "implemented" rather than"overridden", as there _is_ nothing to override.

i prefer using the `override` modifier as a warning sign when someone actually did override a concrete, existing implementation, which i consider a code smell.

**Comment by gokyo** [comment]
I understand your point. 
It is a shame that we don't have an `implemented` modifier in Scala. 

I personally find it useful to quickly see if a method is introduced in the class/object/trait you are reading, or somewhere in its upper hierarchy. 

This is just a suggestion based on my personal preference though. 
So, if you decide to ignore this PR, that's fine.

**Review by rossabaker — COMMENTED** [review]
I generally use the modifier the same as @ritschwumm.

**Comment by armanbilge** [comment]
I also try to use `override` only where its explicitly necessary (i.e. enforced by the compiler). If we want to change the code style for this in Cats I reckon it will be a much bigger PR :)

**Pull request closed without merging**
