### PR TITLE
Revert "up the sample number for `Eq` of function1 for JS"

### PR DESCRIPTION
**Pull request by kailuowang**
This reverts commit 80d56e649c6d2688bf57a3e717f415fcc8fc23c6 which was commit by mistake. Sorry.

### CODE REVIEW

**Comment by kailuowang** [comment]
If two+ maintainers explicitly thumb up the original change (i.e. bump sample number from 10 -> 20 in scalaJs) then I think we can just close this PR.

**Comment by edmundnoble** [comment]
@ceedubs You referring to the reversion or the original PR? For the record I'm thumbs up on the original.

**Comment by ceedubs** [comment]
@edmundnoble oh I don't know....

I guess I'm just giving a 👍 for whatever the value is that doesn't produce false positives in the tests but doesn't make our builds take too long 😬

**Comment by peterneyens** [comment]
It doesn't seem this slows the JS builds down (much), so :+1: 
Closing with 3 thumbs up (that's a first :smiley:),

**Pull request closed without merging**
