### PR TITLE
Test freeJS with FastOptStage to save some CO2

### PR DESCRIPTION
**Pull request by joroKr21**

### CODE REVIEW

**Comment by joroKr21** [comment]
Hmm I didn't see any difference - but now we should be able to run `all` JS tests concurrently - I will try that next.

**Comment by joroKr21** [comment]
It could also depend on the node version / OS - we use a really old one on Travis (4)

**Comment by djspiewak** [comment]
Btw, doing a bit of digging… I think this setting is defaulted.

**Comment by joroKr21** [comment]
> but now we should be able to run all JS tests concurrently - I will try that next.

Done in #3546 - it works

**Pull request merged**
