### PR TITLE
Added Peloton actor library

### PR DESCRIPTION
**Pull request by killaitis**

### CODE REVIEW

**Comment by armanbilge** [comment]
Thanks! Would you be interested in [applying to become an affiliate project](https://github.com/typelevel/governance/issues/new/choose) and being listed on the [Typelevel website](https://typelevel.org/projects/)?

**Comment by killaitis** [comment]
Sure, why not?

**Comment by killaitis** [comment]
So, finally I managed to get the administrative stuff done for the affiliate program (https://github.com/typelevel/governance/issues/136). Maybe you can check this as well.

**Comment by armanbilge** [comment]
Closing, because you are now listed on Typelevel.org. Congrats! :)

**Pull request closed without merging**
