### PR TITLE
Add parTupled methods

### PR DESCRIPTION
**Pull request by iravid**
Pretty sure this isn't binary compatible, but opening anyway to see what MiMa says.

### CODE REVIEW

**Comment by johnynek** [comment]
Shame some of these enrichments aren’t abstract classes so adding methods like this is safe.

**Comment by kailuowang** [comment]
We can generate a new trait with this method and add it to cats.implicits and cats.syntax.all in a bin compat way. Interested?

**Comment by iravid** [comment]
Sure! I’ll look into that next week.

--
Itamar

**Comment by kailuowang** [comment]
@iravid still have time/insterest to continue on this?

**Comment by iravid** [comment]
Very interested, but I don't have the time unfortunately to pick this up in the next week or two. Would be great if someone else can continue :-)

**Comment by barambani** [comment]
if no one is interested in this at the moment I would give it a try

**Comment by LukaJCB** [comment]
Go for it @barambani!

**Comment by iravid** [comment]
Superseded by #2183

**Pull request closed without merging**
