### PR TITLE
Add `orElseRaise` syntax for `ApplicativeError`

### PR DESCRIPTION
**Pull request by kubukoz**

### CODE REVIEW

**Comment by ceedubs** [comment]
Thanks, @kubukoz. Would you mind adding an sbt-doctest example for this? That would help motivate it and would also probably help with the code coverage drop.

**Comment by kailuowang** [comment]
This is a nit: 
This method seems closer to `adaptError` to me, except that it ignores the original error. 
`orElse` is usually associated with recovering. We don't have `adaptError` in `ApplicativeError` but we probably should (at least in the syntax) related issue is https://github.com/typelevel/cats/issues/2685
I have a proposal there. maybe we call this one `adaptErrorTo` or `orRaise`? 
I also agree that we can use at least a doctest.

**Comment by kubukoz** [comment]
I'm back on it. `orRaise` sounds good to me!

**Comment by kubukoz** [comment]
@kailuowang can we get this to the finish line? :)

**Pull request merged**
