### PR TITLE
Update to latest patch versions of scala

### PR DESCRIPTION
**Pull request by ceedubs**
These patch versions include a [security update](http://www.scala-lang.org/news/security-update-nov17.html).

### CODE REVIEW

**Comment by johnynek** [comment]
missing the 2712 plugin on 2.10:
```
[error] (macrosJS/*:coursierResolutions) coursier.ResolutionException: Encountered 1 error(s) in dependency resolution:

[error]     com.milessabin:si2712fix-plugin_2.10.7:1.2.0:```

**Comment by ceedubs** [comment]
Ah bummer. I'll try to get a PR in for the plugin.

**Comment by milessabin** [comment]
PR merged, but unfortunately I won't be able to publish until this evening.

**Comment by milessabin** [comment]
FWIW, I don't believe there's any reason to wait for 2.10.7 to make the release ... the security issue is with the compiler itself rather then binaries built with it, so releasing with 2.10.6 would be just fine.

**Comment by milessabin** [comment]
Hmm ... and you'll need a build for 2.11.11 as well ... on it now ...

**Comment by milessabin** [comment]
Plugin published for 2.10.7 ...

**Pull request merged**
