### PR TITLE
Add Future instances to implicit scope

### PR DESCRIPTION
**Pull request by travisbrown**
See discussion [here](https://github.com/typelevel/cats/pull/3566#issuecomment-674367117). I've not built or run tests locally yet but I think it should work.

### CODE REVIEW

**Comment by barambani** [comment]
This should also resolve this https://github.com/typelevel/cats/issues/3536. Adding it for reference.

**Comment by barambani** [comment]
We could remove `FutureInstances` from here https://github.com/typelevel/cats/blob/a0752346dd0eb2aca54c5a2e153340694d33bada/js/src/test/scala/cats/tests/FutureTests.scala#L18 and the import from here https://github.com/typelevel/cats/blob/a0752346dd0eb2aca54c5a2e153340694d33bada/jvm/src/test/scala/cats/tests/FutureSuite.scala#L3 now. Or you would prefer keep testing the instances through them ? Happy to go on either way 👍 .

**Review by barambani — APPROVED** [review]
Silly me :). The test changes are already in.
Reminder to self: never look at prs from the phone.

**Comment by cb372** [comment]
Once this is merged, it would be handy to have another RC release so I can bump the dependency in `scalafix/build.sbt` on #3566

**Comment by travisbrown** [comment]
Yes, I'm traveling at the moment but could probably publish an RC tonight if this gets merged before then.

**Comment by cb372** [comment]
@travisbrown Don't worry about it, I didn't realise we were publishing snapshots to Sonatype. I was able to use a snapshot. Enjoy your holiday!

**Pull request merged**
