### PR TITLE
Add `Semifield` and `CommutativeSemifield` to algebra

### PR DESCRIPTION
**Pull request by armanbilge**
Introduces a `Semifield` and `CommutativeSemifield` to algebra. I'm going by the [second definition on Wikipedia](https://en.wikipedia.org/wiki/Semifield):
* a commutative monoid for addition (+)
* a group for multiplication (*)

Thanks in advance!

### CODE REVIEW

**Comment by armanbilge** [comment]
@johnynek would you mind reviewing this? Thanks!

**Review by johnynek — APPROVED** [review]
Looks good to me.

Are there examples you have in mind that are not other structures?

Are there any instances we can create that we couldn't fully express before?

**Comment by armanbilge** [comment]
Thanks for the review! I'm using semifields for non-negative reals in my probabilistic programming library, where probabilities are added, multiplied, and divided (but never negative). For example, I have a `LogDouble` type which will have this: https://github.com/armanbilge/schrodinger/blob/main/log-double/src/main/scala/schrodinger/LogDouble.scala#L67

Not sure if this is anything we can add to Algebra itself.

**Comment by johnynek** [comment]
I can't restart the microsite build. Can you push again? I want to make sure it was a flake.

**Comment by armanbilge** [comment]
Absolutely. But this was a known issue, see https://github.com/typelevel/cats/issues/3974#issuecomment-907176663

**Comment by armanbilge** [comment]
@johnynek good to go.

**Comment by benhutchison** [comment]
Thank you @armanbilge & @johnynek for adding `Semifield` & friends 🙏 

I'm guessing the algebra type-classes must sometimes feel obscure and even that no one notices/appreciates the work. So I thought I'd share my story.. 

Having defined a non-negative sub-species of `BigDecimal`, I went looking for the right algebra to implement +, * and /, without negation. And lo and behold, I discovered Semifield was exactly what I needed. At first, I assumed it was part of @non's original vision, but then noticed it is missing from the [algebra docs](https://typelevel.org/cats/algebra.html#ring-like-structures) and got curious how/when it came to be.

On docs, I do think an extra two rows are needed in the [Ring table](https://typelevel.org/cats/algebra.html#ring-like-structures). But then it further qualifies the statement that "every lower structure is also an instance of the structures above it"; I actually wonder if with another two exceptions, that over-generalization has gone past time?

**Comment by armanbilge** [comment]
Thanks!

> I do think an extra two rows are needed in the [Ring table](https://typelevel.org/cats/algebra.html#ring-like-structures).

Indeed!

> I actually wonder if with another two exceptions, that over-generalization has gone past time?

Yes, agree, probably an inheritance diagram would be more useful at this point :) (in addition to the existing table.)

**Pull request merged**
