### PR TITLE
#2947 Added bifold to Bifoldable typeclass

### PR DESCRIPTION
**Pull request by Twizty**
Implemented #2947

### CODE REVIEW

**Comment by Twizty** [comment]
`java.lang.RuntimeException: Could not run jekyll, error: 1` is it a known issue or did I do something wrong?

**Comment by LukaJCB** [comment]
Needs a scalafmt run

**Comment by travisbrown** [comment]
@kailuowang @LukaJCB I think that last merge got this out of sync, which makes review difficult, since there are a lot of extraneous changes in the diff—mind if I rebase to clean it up?

**Comment by LukaJCB** [comment]
Go for it @travisbrown

**Pull request merged**
