### PR TITLE
Add Bifunctor compose, fixes #899

### LINKED ISSUE #899: CompositeBifunctor

### PR DESCRIPTION
**Pull request by adelbertc**

### CODE REVIEW

**Comment by stew** [comment]
:+1:

**Comment by ceedubs** [comment]
Could we add a test of the bifunctor laws for a bifunctor that is created via composition?

**Comment by ceedubs** [comment]
Looks good. Could we a test or two on it?

**Comment by ceedubs** [comment]
@adelbertc sorry I lost track of this one. I'm going to close and reopen to hopefully fix the build failure.

**Comment by ceedubs** [comment]
@adelbertc it looks like you have a compile error due to changes in master.

**Comment by ceedubs** [comment]
Nice! 👍

**Comment by ceedubs** [comment]
Should any changes happen in #1021 to correspond with this being merged?

**Comment by adelbertc** [comment]
@ceedubs Nope, that one is only concerned with type classes over unary type constructors. I have suggestions for what to do with binary type constructor composition here: https://github.com/typelevel/cats/issues/968

**Pull request merged**
