### PR TITLE
Update deprecations to product{L,R} instead of ap{L,R}

### PR DESCRIPTION
**Pull request by rossabaker**

### CODE REVIEW

**Comment by kailuowang** [comment]
oops.

**Comment by rossabaker** [comment]
I asked on cats-dev, should this have targeted the 1.0 branch?

**Comment by rossabaker** [comment]
Retarget to 1.0 pulled in other things already on cats master.  Will cherry-pick and force-push.

**Comment by rossabaker** [comment]
Never mind the cherry-pick-and-push-f.  Discussed on cats-dev, and we want all these master changes back on 1.0 anyway.

**Pull request merged**
