### PR TITLE
Add Seq support to alleycats

### PR DESCRIPTION
**Pull request by joan38**
We have instances for `Iterable` so why not `Seq`?

### CODE REVIEW

**Comment by armanbilge** [comment]
We have `Seq` instances in cats-core :)
https://github.com/typelevel/cats/blob/521c3217a0d59f6ea73512387a4bdd6b291704f1/core/src/main/scala/cats/instances/seq.scala#L34

**Comment by joan38** [comment]
@armanbilge What what what!?

**Comment by joan38** [comment]
How do you make this work then?
https://scastie.scala-lang.org/8sPQmyE5QvSeWXiq4Qe3yg

**Comment by joan38** [comment]
Ok I need `import scala.collection.immutable.Seq`
https://scastie.scala-lang.org/kU6u62BwRfK4dTxYtrrO6Q

**Pull request closed without merging**
