### PR TITLE
minor fix

### PR DESCRIPTION
**Pull request by kailuowang**

### CODE REVIEW

**Comment by LukaJCB** [comment]
How come this compiled? 🤔

**Comment by kailuowang** [comment]
it's legitimate `import` right?

**Comment by kailuowang** [comment]
sorry I wasn't clear. this `import cats.implicits._` is redundant because it's already imported in previous blocks. However for doc purpose, I think we might still want to keep it.

**Comment by LukaJCB** [comment]
Sounds good to me :)

**Pull request merged**
