### PR TITLE
Typelevel ecosystem broken links fix

### PR DESCRIPTION
**Pull request by benkio**
related to the issue #4004 
- [X] Fix the 404 links
- [X] Avoid redirections
- [X] Add `Fly4s`
- [X] upgrade `shell.nix` to the latest 21.05

links checked with https://validator.w3.org/checklink against the page https://typelevel.org/cats/typelevelEcosystem.html

I wasn't able to check it locally yet, having problems in generating the microsite, but this is up for visibility as draft
As soon as I solve the problems with the microsite generations I wish to test it following this article: https://matthewsetter.com/writing-tools/npm-broken-link-checker/

Cheers

### CODE REVIEW

**Comment by benkio** [comment]
this is what I see after moving to the branch and launching
```
nix-shell --pure
sbt docs/makeMicrosite
```

https://pastebin.com/u8DCNGHD

**Comment by rossabaker** [comment]
Thanks!

In a hurry now, but I think the microsite does not compile on the default scala version of the rest of the build.  The ci.yml or old build runs should make clear which version works.

**Comment by benkio** [comment]
looking at `ci.yml`I was able to generate the microsite, but only after upgrading `nixpkgs` to the last version in order to have access to later `jekyll` and `ruby`. I think we can move forward from the `18.09` release.

I runned [linkchecker](http://wummel.github.io/linkchecker/index.html) and [this is the result of 5 min scanning](https://pastebin.com/LbBBwxFT)

**Review by rossabaker — APPROVED** [review]
Nice work!

Markdown references could be used to DRY up FS2 or other repeated links, but it's not really that big a deal.

**Comment by benkio** [comment]
> Nice work!
> 
> Markdown references could be used to DRY up FS2 or other repeated links, but it's not really that big a deal.

Just added the link references for duplicated links

**Review by rossabaker — APPROVED** [review]

**Pull request merged**
