### PR TITLE
New Proposal for the Cats Microsite

### PR DESCRIPTION
**Pull request by juanpedromoreno**
This PR brings a new proposal for the [Typelevel Cats website](http://typelevel.org/cats/) microsite. 

It's made thanks to the https://github.com/47deg/sbt-microsites plugin and:

* Provides the `override.css` file and the images resources.
* Removes the versioned [site](https://github.com/typelevel/cats/tree/master/docs/src/site).
* Modifies the src/main/tut resources according to: root files, typeclasses and datatypes.
* Updates the current documentation.
* Other minor tweaks to be able to generate the site successfully.

The generated [site](https://github.com/typelevel/cats/tree/master/docs/src/site) has been removed since is not needed from now on. As you can see in the [contributing.md](https://github.com/47deg/cats/blob/master/CONTRIBUTING.md#generating-the-site) file, the `site` can be generated each time on the fly. 

If you want to test locally you need [Jekyll](https://jekyllrb.com/) locally, depending on your platform, you might do this with:

```bash
yum install jekyll

apt-get install jekyll

gem install jekyll
```

Once you have installed it, you could perform the following steps:

* Build the microsite:

```bash
sbt docs/makeMicrosite
```

* Then, to visualize the website in your browser, in a shell, navigate to the generated site directory in `docs/target/site`
* Start jekyll with `jekyll serve`
* Navigate to http://localhost:4000/cats/

Please, review at your convenience. Thanks!

Join-effort from the 47Deg team :)

### CODE REVIEW

**Comment by juanpedromoreno** [comment]
cats

**Comment by kailuowang** [comment]
Thanks very much!  
Can you expand on "on the fly" a little bit more? What triggers generating the site and push it to gh-page branch? I could not find it on sbt-microsites doc.

**Comment by juanpedromoreno** [comment]
Sure, I guess site publication are disabled right now.

https://github.com/typelevel/cats/blob/449e0b04d362843cd5bc129d933397ae0ad49011/scripts/travis-publish.sh#L22

Therefore, in the meantime this publish should performed by hand in the same way until now (`sbt ghpagesPushSite `), but in this case from the `docs/target/site` path (that is generated on the fly when you run `run makeMicrosite`). Does it make sense?

https://github.com/typelevel/cats/blob/master/CONTRIBUTING.md#publishing-the-site-to-github

I'm sorry about the sbt-microsites plugin documentation, it's still a WIP, nevertheless we hope to have ready all the plugin docs by this week.

**Comment by kailuowang** [comment]
Ah that makes sense. Thanks! Is there a plan to release sbt-microsites? Looks very helpful.

**Comment by juanpedromoreno** [comment]
Yep, it'll be released very soon!

**Comment by BennyHill** [comment]
@juanpedromoreno This looks very nice!!

One thing that the cats docs do not currently do/have is support for current/previous versions - eg 
 https://www.scala-js.org/doc/all-api.html and http://tpolecat.github.io/doobie-0.3.0/00-index.html

Had you thought about this as part of your new plugin?

**Comment by juanpedromoreno** [comment]
@BennyHill Not yet, but we'll do. Thanks!

**Comment by BennyHill** [comment]
@juanpedromoreno I know your plugin is still WIP, 0.1.0 etc - I just thought I should pipe in with something that was on a TODO list at some point, lest it be forgotten. Looks cools already, btw :smile_cat:

**Comment by kailuowang** [comment]
LGTM, I am wondering if we should wait for sbt-microsites release before merging this one in.

**Comment by juanpedromoreno** [comment]
:thumbsup: We're working in the `sbt-microsites` release at this moment, we'll let you know once everything is ready. Thanks!

**Comment by jhzab** [comment]
Two small comments:

1. Is there some mechanism to include the current release version in the index.md file? I think automating this makes sense.
2. I was really surprised that I could actually build cats with the sbt default memory settings, but could not build the site with 1GB.

**Comment by juanpedromoreno** [comment]
@jhzab For comment 1, potentially, it could be accomplished with `tut`, but I have to give a try.

For point 2, yep, you're right, compiling tut documents could take some time and memory (couple of GB of `Xmx` should be enough).

**Comment by kailuowang** [comment]
@juanpedromoreno thanks again. It looks like sbt-microsites has been released. I wonder if you have time to update this PR? Otherwise I can pick it up.

**Comment by juanpedromoreno** [comment]
Sure @kailuowang . I'll do it this afternoon. Thanks!

**Comment by juanpedromoreno** [comment]
@kailuowang Done ;)

**Comment by adelbertc** [comment]
Looks like the 2.11 build was failing, not sure why, I've restarted it.

**Comment by juanpedromoreno** [comment]
Now it's green, thanks @adelbertc

**Comment by kailuowang** [comment]
👍  thanks a lot!

**Comment by ceedubs** [comment]
Thanks a bunch, @juanpedromoreno! This looks really nice. I'm hoping I can find the time to take a closer look this evening or tomorrow.

**Comment by juanpedromoreno** [comment]
Hey @ceedubs @kailuowang, is there anything else I can do about this PR? Just let me know. Thanks!

**Comment by kailuowang** [comment]
@juanpedromoreno LGTM.

**Comment by ceedubs** [comment]
@juanpedromoreno I'm sorry for the long delay on this. Life has gotten busy. I won't get a chance to look at this in the next several days. It looks like @kailuowang already gave a 👍. @adelbertc or @tpolecat (or anyone else) would you want to review this?

**Comment by juanpedromoreno** [comment]
Sure, no problem @ceedubs

**Comment by adelbertc** [comment]
I have approximately negative web dev experience but I looked at the changes and looks OK to me? 👍 from me.

**Comment by kailuowang** [comment]
Thanks @adelbertc merging with two thumbs up.

**Comment by adelbertc** [comment]
@juanpedromoreno @kailuowang How do we get this published on typelevel.org/cats ?

**Pull request merged**
