### PR TITLE
Use uber import in docs. (#1026)

### PR DESCRIPTION
**Pull request by cranst0n**

### CODE REVIEW

**Comment by non** [comment]
Love it! Thanks so much. 👍

**Comment by ceedubs** [comment]
Oh fantastic @cranst0n. Thanks a bunch! Based on repeated Gitter questions, I think this will help a lot of people.

**Comment by cranst0n** [comment]
@ceedubs @non 

I forgot to mention an issue that came up when making these changes. Specifically in `optiont.md` in the tut docs.

When I replaced the respective instances of `import cats.std.future._` tut fails to compile it:

```scala
[tut] *** Error reported at optiont.md:69
<console>:25: error: ambiguous implicit values:
 both value catsStdBimonadForFunction0 in trait Function0Instances of type => cats.Bimonad[Function0]
 and value catsStdInstancesForList in trait ListInstances of type => cats.Traverse[List] with cats.MonadCombine[List] with cats.MonadRec[List] with cats.CoflatMap[List]
 match expected type cats.Applicative[F]
         l <- OptionT.fromOption(lastnameO)
```

I didn't make the change because of this reason but I suppose it should be addressed in some way?

**Comment by ceedubs** [comment]
@cranst0n oh thanks for the heads up. It looks like after changing the imports you need to change that line to `OptionT.fromOption[Future](lastnameO)`. I'm not really sure why that is. I'd be inclined to go ahead and change to the uber imports and do that anyway.

**Pull request merged**
