### PR TITLE
Add diagram of typeclass hierarchy continue #822

### PR DESCRIPTION
**Pull request by kailuowang**
Obviously this is just a start, we can improve it once we have a starting point.

### CODE REVIEW

**Comment by kailuowang** [comment]
diagram result
687474703a2f2f672e67726176697a6f2e636f6d2f673f253041253230253230646967726170682532304725323025374225304125323025323025323025323061697a652532303d253232342c342532323b253041253230253230253230253230656467652532302535426469723d6261636b2535442530

**Comment by BennyHill** [comment]
Just in case it's been forgotten - @non's prior art:

http://plastic-idolatry.com/erik/cats-graph.png

http://plastic-idolatry.com/erik/cats-graph2.png

**Comment by kailuowang** [comment]
Didn't forget that but I like this one because it's text specified and thus easy to change.

**Comment by adelbertc** [comment]
👍

**Comment by travisbrown** [comment]
:+1:, this looks great. I don't know anything about Gravizo—I don't suppose it's practical to have this rendered locally during the build?

**Comment by kailuowang** [comment]
@travisbrown the image is generated on Gravizo server and displays in the viewer - in most cases, the browser.  Merging with 2 thumbs up.

**Comment by travisbrown** [comment]
@kailuowang Right—I was just wondering if it would be possible to do without relying on a third-party (commercial) service, since it looks like the service is just running graphviz for you. I'm happy to see this merged as-is, though.

**Comment by kailuowang** [comment]
I see. Not familiar with it myself (I merely resurrect @rklaehn's PR). Upon some research there are quite a few tools that can render dot locally.  For example, https://github.com/drdozer/graphviz-s/tree/102215679c7da01689d3e4aade5f38782dbdb142. It might take some work to integrate it with sbt (this lib is 2.11). I agree it's less optimal to rely on a 3rd party commercial service.

**Pull request merged**
