### PR TITLE
Add typeclasses for immutable.Seq

### LINKED ISSUE #1222: No typeclasses for Seq
I see there are typeclasses under cats.std for List and Vector (among others), but none for Seq. Is there a reason no typeclasses for Seq are provided? If it's simply that there's been no demand previously, then I'm happy to raise a PR to add this.

### PR DESCRIPTION
**Pull request by JosephMoniz**
Adds type class instances for `immutable.Seq`. This is based off of the implementations of the `List` and `Vector` typeclasses.

Closes #1222

### CODE REVIEW

**Review by LukaJCB — COMMENTED** [review]
Thanks a bunch for this PR, it's very thorough! :) I think we should future proof a little bit, based on my experiences in https://github.com/typelevel/cats/pull/3552

**Comment by JosephMoniz** [comment]
Thanks for the review @LukaJCB!

I went ahead and lowered the priority of the `immutable.Seq` instances you called out. Hopefully they wont cause any problems for dotty going forward now.

**Review by LukaJCB — APPROVED** [review]
Excellent, thank you!

**Review by djspiewak — APPROVED** [review]
This is quite nice!

**Pull request merged**
