### PR TITLE
Add Foldable.intercalate

### PR DESCRIPTION
**Pull request by peterneyens**
Add an element between all the existing elements while folding.

### CODE REVIEW

**Comment by ceedubs** [comment]
Thanks @peterneyens. This looks good to me. The string example is the main way I could see myself using this in the real world. Out of curiosity, did you have any other use-cases in mind?

If we add this, should we add something like `intercalate1` (to follow the naming convention of `traverse1_` and `sequence1_`) to `Reducible` that requires only a `Semigroup` as opposed to a `Monoid`?

**Comment by peterneyens** [comment]
- Mostly as an alternative for #1518 (for strings) indeed. 
- Another use case when I was thinking about something like `intercalate` was pretty printing (specifically [here](https://github.com/47deg/fetch/blob/master/debug/shared/src/main/scala/debug.scala#L29) in fetch).
- I think @tpolecat asked once if cats had `intercalate`, maybe he had another use case ?

I added `Reducible.intercalate1`, forgot last night that we could lower the requirement to `Semigroup` for `Reducible`.

**Comment by ceedubs** [comment]
@peterneyens would you be willing to add a test for `intercalate1`? It'd probably be nice to hit the overridden `intercalate` in `Reducible` too.

**Comment by ceedubs** [comment]
Actually I guess the sbt-doctest examples are pretty legitimate tests. 👍 from me.

**Comment by ceedubs** [comment]
Good points @johnynek.

**Comment by tpolecat** [comment]
@peterneyens yeah I need it for generating SQL … I also did a [more general thing](https://github.com/tpolecat/doobie/blob/series/0.3.x/yax/core/src/main/scala/doobie/util/foldable.scala#L22) that takes start/end brackets as well as the delimiter, which generalizes `mkString` and is useful but it's hard to think of a good name.

In any case 👍 for this, with test improvements as suggested above.

**Comment by adelbertc** [comment]
👍 after test improvements.

**Comment by peterneyens** [comment]
Thanks for the pointers @johnynek 

- I used `mkString` and `F[String]` in the tests instead.
- I added a test for `intercalate1` (it was already tested before through the overridden `intercalate` which is tested because `ReducibleCheck` extends `FoldableCheck`, but is probably better to be explicit).
- I added a doctest for `intercalate` and `intercalate1` with a one item foldable. The one element foldable case is already covered by the property tests, right ?

**Comment by johnynek** [comment]
+1 on this.

**Comment by adelbertc** [comment]
Let's do this

**Comment by johnynek** [comment]
one bummer about this: using it to write `mkString` will be `O(N^2)` in cost. This is one of the problems that `combineAll` was designed to deal with. Not sure the best way to go here. For integers it is a waste, but for a lot of strings a huge win.

The simplest thing would be to use `Foldable.toList` to build a list, then intercalate only on the list, then call combineAll on the list. I guess that might be the right way to go actually.

**Comment by peterneyens** [comment]
@johnynek, so something like the following ?

```scala
def intercalate[A](fa: F[A], a: A)(implicit A: Monoid[A]): A =
  combineAll(intersperseList(toList(fa), a))

private def intersperseList[A](xs: List[A], x: A): List[A] = {
  val bld = List.newBuilder[A]
  val it = xs.iterator
  if (it.hasNext) {
    bld += it.next
    while(it.hasNext) {
      bld += x
      bld += it.next
    }
  }
  bld.result
}

// Reducible 
def intercalate1[A](fa: F[A], a: A)(implicit A: Semigroup[A]): A =
  reduce(intersperseList(toList(fa), a))
```

**Comment by johnynek** [comment]
Exactly.

**Pull request merged**
