### PR TITLE
Update SBT and SBT plugin versions

### PR DESCRIPTION
**Pull request by travisbrown**
I just noticed while working on #1253 that some of these versions are out-of-date. I ran the benchmarks locally to confirm that the sbt-jmh update doesn't break anything.

### CODE REVIEW

**Comment by kailuowang** [comment]
Looks like build is going to fail.  but #1256 should fix build

**Comment by travisbrown** [comment]
@kailuowang Great, thanks—I'll rebase after that's merged. (For the record `sbt validate` passes locally if I bump the memory in `.jvmopts`.)

**Comment by kailuowang** [comment]
@travisbrown thanks for the hint. I tried the same approach in this PR https://github.com/typelevel/cats/pull/1257 but it failed pretty miserably (maybe travis just doesn't have that much memory? )

**Comment by mikejcurry** [comment]
@kailuowang -I understood Travis limitation in terms of memory to be 3G. From Travis FAQ, though don't know how up to date that is.

> What hardware are my tests running on?
> We use dedicated hardware to ensure full speed for your tests. You have 3GB of memory and up to 2 cores available. Your tests are running directly off SSDs with the most common databases optimized to run off RAM disks.

**Comment by travisbrown** [comment]
Just rebased this to try out #1256 with the updates.

**Comment by johnynek** [comment]
👍

**Comment by fthomas** [comment]
:+1:

**Pull request merged**
