### PR TITLE
Update to ScalaCheck 1.13.0

### PR DESCRIPTION
**Pull request by fthomas**
I haven't tested this locally, so let's see how `Cogen` affects Cats.

### CODE REVIEW

**Comment by travisbrown** [comment]
I ran into ScalaTest runtime errors when I tried this for circe, so I'd guess we'll need to wait for a new milestone here as well.

**Comment by fthomas** [comment]
The CI failed because of errors like this:
    
    [error] /home/travis/build/typelevel/cats/laws/src/main/scala/cats/laws/discipline/AlternativeTests.scala:30:
    could not find implicit value for parameter a3: org.scalacheck.Arbitrary[A => B]

**Comment by mikejcurry** [comment]
This could possibly be related to #856, which added a temporary Int => Boolean arbitrary instance. This should be superfluous with the new scalacheck so can probably be removed.

I can investigate later, but won't be home for a few hours to do so.

**Comment by ceedubs** [comment]
See also https://github.com/scalatest/scalatest/issues/837

**Comment by fthomas** [comment]
Ok, so updating ScalaCheck is more involved than just updating the version number. Since I currently don't have enough time to work on this, I'll close this PR so that someone else can take over.

**Pull request closed without merging**
