### PR TITLE
Remove simulacrum

### PR DESCRIPTION
**Pull request by BalmungSan**
This is a dumb search and replace and is mostly intended as a conversation starter and maybe as a base for someone else to pick up and finish more advanced changes.

### CODE REVIEW

**Comment by armanbilge** [comment]
For context, see the following PRs where instructions to run scalafix simulacrum in the Cats' sources were more trouble than help.
- https://github.com/typelevel/cats/pull/4209#discussion_r878637013
- https://github.com/typelevel/cats/pull/4146#issuecomment-1062706329

See also plans to enable "organize imports" and other helpful scalafixes via sbt-typelevel, which would have friction with the simualcrum scalafixes in this repository.
- https://github.com/typelevel/sbt-typelevel/pull/274

**Review by johnynek — APPROVED** [review]
Nice that this can be removed without a Mima issue.

**Comment by armanbilge** [comment]
We can also remove this file.
https://github.com/typelevel/cats/blob/15f75f716288ceb76c368b6ca73c7d1afe7c5c87/.scalafix.conf#L1-L7

**Comment by BalmungSan** [comment]
I just removed more references to **simulacrum**.

**Review by armanbilge — APPROVED** [review]
Thank you for spear-heading this change.

**Pull request merged**
