### PR TITLE
Fix type signature of `productL` in cats glossary

### PR DESCRIPTION
**Pull request by mtomko**
Thank you for contributing to Cats!

This is a kind reminder to run `sbt prePR` and commit the changed files before submitting.

### CODE REVIEW

**Comment by mtomko** [comment]
Oh, doh, I think I misunderstood the instructions about `sbt prePR`.

**Comment by mtomko** [comment]
Just to confirm `sbt prePR` didn't appear to change any files, the reminder is only to be sure I committed the files I _meant_ to change.

**Comment by kailuowang** [comment]
@mtomko sorry the instruction wasn't clear. `sbt prePR` reformats the code and runs a couple of other checks. If your code already conforms to the format settings then it won't change anything. But if it did you would need to include those changes in the PR as well.

**Comment by mtomko** [comment]
I mentioned some other possible changes to the nomenclature file in gitter, which I'm happy to add to this PR. I'll summarize them here. If you want me to add them let me know and I'll include them in separate commits:

First, in the signature for `flatTap`, it currently reads:
`F[A] => (A => F[-]) => F[A]`, but it might be clearer written `F[A] => (A => F[B]) => F[A]`.

Secondly, the word `Constraints` appears to be misspelled as "Constrains" in a few tables. If you'd rather keep things in separate PRs, or feel that the changes aren't important, that's fine with me, too.

**Comment by mtomko** [comment]
Got it, thanks for the information!

**Pull request merged**
