### PR TITLE
Upgrades sbt version on the 2.11 branch to 1.3.3 to match master

### PR DESCRIPTION
**Pull request by jackcviers**
Thank you for contributing to Cats!

This is a kind reminder to run `sbt +prePR` and commit the changed files, if any, before submitting.

### CODE REVIEW

**Comment by jackcviers** [comment]
@travisbrown I think something went wrong on the travis server -- all I did was upgrade the sbt build version in build.properties and it is reporting a mima exception, and also is failing to compile there. Builds fine on sbt 1.3.3 on my machine. Need a little help here.

**Comment by travisbrown** [comment]
@jackcviers I don't exactly understand what's going on with the failure but I think #3139 should work.

**Comment by travisbrown** [comment]
Superseded by #3139.

**Comment by jackcviers** [comment]
Thank you @travisbrown

**Pull request closed without merging**
