### PR TITLE
Add NonEmptyList#toNes (issue #2346)

### PR DESCRIPTION
**Pull request by CucumisSativus**
The last missing pull request for #2346

### CODE REVIEW

**Comment by hepin1989** [comment]
Why.not toSet or toNonEmptySet

**Comment by satansk** [comment]
@hepin1989 Beacuse there are already some codes where `toNes` refers to `toNonEmptySet`. In fact, this is confusing sometimes, beacuse it can be interperted as `toNonEmptyStream` too.

**Comment by CucumisSativus** [comment]
@hepin1989 Everything that @satansk + the fact I wanted to be consistent with the rest of naming from this issue where I implemented NonEmptyMap#toNel and NonEmptyList#toNem. I think that `.toSet` might because it does not mention that this set should be non empty. 

If you guys think that this naming is misleading, i'm not really attached to it.

**Comment by CucumisSativus** [comment]
Sorry for the mess in commits, screwed a bit with merging and then everything escalated quickly.

**Comment by CucumisSativus** [comment]
The build failed because of `Java HotSpot(TM) 64-Bit Server VM warning: INFO: os::commit_memory(0x000000078ce4e000, 857415680, 0) failed; error='Cannot allocate memory' (errno=12)`. Could someone restart it?

**Pull request merged**
