### PR TITLE
Reverted binary incompatible changes to generated parallel syntax

### PR DESCRIPTION
**Pull request by barambani**
In relation to this PR https://github.com/typelevel/cats/pull/2692, I realise only now that the same problem I had with the Semigroupal syntax is also affecting the boilerplate parallel syntax. I reverted the change to the generator and added a MimaExceptions test.

### CODE REVIEW

**Comment by kailuowang** [comment]
Just so that I know that the MimaException test still works, the test you added failed with the `private val` change you made?

**Comment by barambani** [comment]
The problematic bit is the syntax ops extending AnyVal. With 
```scala
private[syntax] final class Tuple${arity}ParallelOps[M[_], ${`A..N`}](private val $tupleTpe)
```
the test result is 
```
[info] MimaExceptionsTest:
[info] - is binary compatible
[info] Run completed in 960 milliseconds.
[info] Total number of tests run: 1
[info] Suites: completed 1, aborted 0
[info] Tests: succeeded 1, failed 0, canceled 0, ignored 0, pending 0
[info] All tests passed.
[success] Total time: 99 s
```

but changing it to 
```scala
private[syntax] final class Tuple${arity}ParallelOps[M[_], ${`A..N`}](private val $tupleTpe) extends AnyVal
```
the test fails
```
[info] MimaExceptionsTest:
[info] catsBC.MimaExceptionsTest *** ABORTED ***
[info]   java.lang.NoSuchMethodError: cats.implicits$.catsSyntaxTuple3Parallel(Lscala/Tuple3;)Lcats/syntax/Tuple3ParallelOps;
[info]   at catsBC.MimaExceptions$.isBinaryCompatible(MimaExceptions.scala:30)
[info]   at catsBC.MimaExceptionsTest$$anonfun$1.apply(MimaExceptionsTest.scala:7)
[info]   at catsBC.MimaExceptionsTest$$anonfun$1.apply(MimaExceptionsTest.scala:7)
[info]   at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:20)
[info]   at org.scalatest.FunSuiteLike$$anon$1.apply(FunSuiteLike.scala:186)
[info]   at org.scalatest.TestSuite$class.withFixture(TestSuite.scala:196)
[info]   at org.scalatest.FunSuite.withFixture(FunSuite.scala:1560)
[info]   ...
```

**Comment by kailuowang** [comment]
Ah didn't realize that it wasnt value class and  you changed that. I think we should still make the call private.

**Comment by barambani** [comment]
Makes sense. I will do it 👍

**Comment by barambani** [comment]
could the 2.13's travis job be restarted ?
```
CommutativeGroup[BigDecimal].commutativeGroup.associative *** FAILED ***
  GeneratorDrivenPropertyCheckFailedException was thrown during property evaluation.
   (Discipline.scala:14)
    Falsified after 4 successful property evaluations.
    Location: (Discipline.scala:14)
    Occurred when passed generated values (
      arg0 = 7.11522893613707E+63,
      arg1 = -1.6701798045816614E+43,
      arg2 = -1.1744341123863878E+45
    )
    Label of failing property:
      Expected: 7.115228936137069998808864089567796E+63
      Received: 7.115228936137069998808864089567795E+63
```

**Pull request merged**
