### PR TITLE
Backporting ifF for scala 2.11

### PR DESCRIPTION
**Pull request by sdrafahl**
Backporting ifF for scala 2.11.

### CODE REVIEW

**Comment by travisbrown** [comment]
This unfortunately can't be added directly to the `Functor` trait on 2.11 because it breaks binary compatibility. You can add it to functor syntax via the `BinCompat` approach, and if you really wanted you could add it to `Functor` via an enrichment method.

**Comment by sdrafahl** [comment]
@travisbrown Could you show me an example of the BinCompat approach? I have an idea of how to do the implicit class approach but would like to consider both?

**Comment by travisbrown** [comment]
@sdrafahl [This PR](https://github.com/typelevel/cats/pull/2609/files) is a good example of what's necessary (it's quite painful, unfortunately, which is why we've dropped 2.11 on master :smile:).

**Comment by larsrh** [comment]
I'm closing all 2.11-related tickets since there is not enough community interest in further releases.

**Pull request closed without merging**
