### PR TITLE
Add FlatMapRec, MonadRec.

### PR DESCRIPTION
**Pull request by TomasMikula**
See #616.

### CODE REVIEW

**Comment by ceedubs** [comment]
I don't understand why, but it looks like the build is failing with this:

```
[error] /home/travis/build/typelevel/cats/core/src/main/scala/cats/MonadRec.scala:5: not found: value FlatMapRec
[error] @typeclass trait MonadRec[F[_]] extends Monad[F] with FlatMapRec[F]
[error]  ^
[error] /home/travis/build/typelevel/cats/core/src/main/scala/cats/MonadRec.scala:5: not found: value FlatMapRec
[error] @typeclass trait MonadRec[F[_]] extends Monad[F] with FlatMapRec[F]
[error]  ^
```

**Comment by adelbertc** [comment]
So when I (halfway) implemented this many moons ago I tried to write a test that would test the stack safety of implementations.. is that possible?

**Comment by TomasMikula** [comment]
@ceedubs strange, I haven't seen that error. But I fixed a Scaladoc link so now the travis build started again.

**Comment by TomasMikula** [comment]
@adelbertc Yeah, but that should go to #1041 then.

**Comment by TomasMikula** [comment]
2.11.8 test is succeeding now. 2.10.6 failed and I can't even tell why.

**Comment by adelbertc** [comment]
@TomasMikula is it possible to get this and https://github.com/typelevel/cats/pull/1041 put into 1 PR? either this one or that one?

**Comment by TomasMikula** [comment]
@adelbertc sure, #1041 contains the commit of this PR as well.

**Comment by adelbertc** [comment]
Closed in favor of #1041

**Pull request closed without merging**
