### PR TITLE
Adds syntax for Strings to parse numbers and booleans.

### PR DESCRIPTION
**Pull request by cwmyers**
Includes tests for `parseInt`, `parseLong`, `parseByte`, `parseShort`, `parseDouble`, `parseFloat` and `parseBoolean`.

This also tests the typeclass for `Show`.

### CODE REVIEW

**Comment by ceedubs** [comment]
Thank you for your contribution, @cwmyers.

I think that these methods are useful, but I find myself wondering whether they fit into cats. They fall into the category of "helper methods" as opposed to providing abstractions or data types that are useful for functional programming.

What do other people think?

**Comment by cwmyers** [comment]
Hi @ceedubs 

You have a fair point.  This PR can from my assessment of moving our code base from Scalaz to cats.  I'm conscious that cats' goals may not necessarily be a drop in replacement for scalaz but these parse functions were useful to us.  Also, I was wondering of the overhead of bringing an extra helper library that returned cats data types.

That said, if the community recommends this goes to a helper library I'm happy for that to happen.  Is there general interest in incepting a helper library project?

Many thanks,
Chris

**Comment by travisbrown** [comment]
This question has come up a few times, and as far as I know nobody's actually started a project for functions like this, but I think one would be very useful.

I agree that these don't belong in cats-core, but I'd personally be happy to see something like a cats-misc module in the cats repo—that way when people come from Scalaz the path is clear. I guess this could happen outside the cats repo as well, but I'm afraid that that'd mean we just keep kicking the can down the road until someone comes up with a funny project name or whatever.

**Comment by fsvehla** [comment]
Could this be part of Cats if it would conform to the idea of `Read`?

**Comment by benhutchison** [comment]
Hi @cwmyers I think your string enrichments are similar to #791 ? Seems clear that a module to support these kinds of extensions is needed somewhere. I posed some questions in #791 I was hoping to get feedback on, but no response yet, will bump it in gitter since you've hit same issue...

**Comment by DavidGregory084** [comment]
Can I suggest that you call this `fat-cats` :wink:

**Comment by cwmyers** [comment]
I'm going to close this PR as @benhutchison has created the mouse project for non-core helper features.

This PR has moved here: https://github.com/benhutchison/mouse/pull/1

**Pull request closed without merging**
