### PR TITLE
fix URLs

### PR DESCRIPTION
**Pull request by dlwh**

### CODE REVIEW

**Comment by adelbertc** [comment]
:+1:

**Comment by fthomas** [comment]
Those URLs already redirect to http://typelevel.org/cats/ and http://typelevel.org/cats/api/#package. Should we just use the typelevel.org links?

**Comment by dlwh** [comment]
I'm personally totally happy for it to be whatever. Just figured the 404 wasn't good :-)

**Comment by fthomas** [comment]
Agreed. :-)

#837 which I just merged also updated the website and Scaladoc URLs. I'm therefore closing this PR. Sorry for the duplicated effort.

**Pull request closed without merging**
