### PR TITLE
Remove catalysts dependency

### PR DESCRIPTION
**Pull request by travisbrown**
The catalysts dependency has proven to be a drag on every update (right now it seems to be [blocking a release for 2.13.0-RC1](https://github.com/typelevel/cats/issues/2776)) and at this point it's almost completely unused, so I'm proposing that we just scrap it.

There's some dead code in `LawTests` that uses catalysts's `TypeTagM`, but it is unused and hasn't been touched since 2016, so I just scrapped it. Otherwise the only thing catalysts is used for is to check whether the current build is Scala.js in order to set appropriate test sizes.

In my view this really should be done with separate code trees, but to keep this PR simple I just introduced a new (package private) `cats.platform.Platform` that duplicates the ~dozen lines of code Cats needs from catalysts.

MiMa says this change is fine, all tests pass as usual with no changes (apart from the `Platform` import), etc.

r? @SethTisue @kailuowang

### CODE REVIEW

**Comment by kailuowang** [comment]
Thanks so much for taking this on. I believe this is the right thing to do.

**Comment by SethTisue** [comment]
one less thing to worry about :+1:

**Comment by travisbrown** [comment]
I ran `validateJVM` and `prePR` and thought that would be enough to confirm that the build works, but apparently it's not. Fixing the alleycats issue now (and trying not to get extremely frustrated that `alleycats` is used as a top-level package and shares no path with `cats`…).

**Comment by kailuowang** [comment]
I am on my phone, the code changes look good to me, but GitHub didn't really show the full path of the rename, so it appears that there is no actual path change. I am curious what they are.

**Comment by kailuowang** [comment]
replaced by #2792

**Comment by kailuowang** [comment]
@travisbrown I spoke too soon in #2792, there is a conflict and can't be resolved throught github ui. Would it be too much to ask you to resolve it?

**Comment by travisbrown** [comment]
@kailuowang Merged, thanks.

**Pull request merged**
