### PR TITLE
A new dedicated cats ecosystem page(s) #3121

### PR DESCRIPTION
**Pull request by benkio**
Creating a list of Typelevel related libraries and projects.

For now, I didn't include the "How to" section mentioned in the issue. It Still needs some grooming around its content.
I think it can have its own section, or be merged with FAQ, and have a separate following PR for that.

### CODE REVIEW

**Comment by kailuowang** [comment]
Thanks so much! Would you create a separate page and menu item for it instead of adding it as a section under colophon as suggested in your comment in #3121? Sorry I didn't get to respond to you earlier. 
I agree that the how to section can be a separate PR.

**Comment by benkio** [comment]
> Thanks so much! Would you create a separate page and menu item for it instead of adding it as a section under colophon as suggested in your comment in #3121?
I reverted the changes. Now It's a separate page/menu :wink:

**Review by larsrh — APPROVED** [review]
Let's do this!

**Review by LukaJCB — APPROVED** [review]
Thank you so much! :)

**Review by tpolecat — COMMENTED** [review]
This is great! 👍

**Comment by benkio** [comment]
Thanks you all guys 🙏🙏🙏

**Pull request merged**
