### PR TITLE
2.1.0-RC3 follow-up

### PR DESCRIPTION
**Pull request by travisbrown**
This PR includes the release commit tagged by sbt-release—if you're merging it please be sure to choose the merge commit option.

### CODE REVIEW

**Comment by travisbrown** [comment]
@kailuowang Thanks for merging! But it really would be better not to squash these post-release PRs (see the comment in the description above), since now the `v2.1.0-RC3` release tag doesn't point to a commit on master.

We could delete the tag and push a new one, but that could cause other problems. I guess it doesn't matter all that much in this case since this is a pre-release, but we really don't want to be in this situation for actual releases.

**Comment by travisbrown** [comment]
This also means I'll have to update and force-push the `2.1.0` tag, because otherwise it'll end up with noisy merge commits going both ways (i.e. it can't be fast-forwarded to master now, and if we merge-commit master onto it that will require another merge commit at the next release). I'll do that when I'm back at my desktop later today.

**Comment by travisbrown** [comment]
Okay, just force-pushed `2.1.0` branch.

I also deleted the broken `v2.1.0-RC3` and pushed a new one. I had to re-set the tag in the release but otherwise it seems fine. The old tag was just a few hours old so hopefully this won't be too annoying for people (I think having accurate release tags is worth it).

**Comment by kailuowang** [comment]
I apologize. It's my bad. I merged from my phone and my brain short circuited. Sorry about that, thanks for cleaning up the mess.

**Comment by travisbrown** [comment]
@kailuowang No worries, the clean-up was actually really easy!

**Pull request merged**
