### PR TITLE
Issue #4631: Make Later covariant

### PR DESCRIPTION
**Pull request by yanns**
Same as https://github.com/typelevel/cats/pull/937

fixes https://github.com/typelevel/cats/issues/4631

### CODE REVIEW

**Comment by satorg** [comment]
Thank you for the fix!
Note that `Later` is one of the `Leaf` descendants. The other two are `Always` and `Now`.
I wonder if it makes sense to make all the "leaves" covariant together rather than just one of them?
I feel it could be rather confusing to have one `Leaf` covariant and the other two invariant.

**Comment by yanns** [comment]
> Thank you for the fix! Note that `Later` is one of the `Leaf` descendants. The other two are `Always` and `Now`. I wonder if it makes sense to make all the "leaves" covariant together rather than just one of them? I feel it could be rather confusing to have one `Leaf` covariant and the other two invariant.

I had the same thoughts when changing `Later`, but was not feeling confident enough to make more changes than the very strict necessary. Thanks for the quick feedback! I've now adapted all leafs of `Eval`.

**Comment by satorg** [comment]
@yanns , I lost tracking of your PR, sorry. Would you mind updating it to the most recent "main" such that we could re-run all the checks please? Thank you!

**Comment by yanns** [comment]
@satorg thanks for coming back! I've updated the branch. The tests on scala 2.12 with scala native are failing, without any good error message.

**Comment by yanns** [comment]
now all tests have passed

**Review by satorg — APPROVED** [review]
Thank you!

**Comment by yanns** [comment]
When does a PR get merged? I could find any process described in https://github.com/typelevel/cats/blob/main/CONTRIBUTING.md ?
Do you wait for 2 reviews?

**Review by johnynek — APPROVED** [review]

**Pull request merged**
