### PR TITLE
Scala 2.11 scalafmt master

### PR DESCRIPTION
**Pull request by jackcviers**
Thank you for contributing to Cats!

This is a kind reminder to run `sbt +prePR` and commit the changed files, if any, before submitting.

### CODE REVIEW

**Comment by travisbrown** [comment]
Once #3139 is merged I think you'll be able to rebase and CI will pass.

**Comment by jackcviers** [comment]
@travisbrown I don't think this is quite right, if you take a look at the bincompat test on travis now, no mima artifacts get set, so it never checks binary compatibility.



https://travis-ci.org/typelevel/cats/jobs/611168027#L341-L388

**Comment by travisbrown** [comment]
@jackcviers Right, you can run `show mimaPreviousArtifacts` to confirm that previous versions are configured for core, kernel, and free.

**Comment by travisbrown** [comment]
Closing this since I just updated everything at once in #3139.

**Pull request closed without merging**
