### PR TITLE
Add toNestedValidated and toNestedValidatedNel

### PR DESCRIPTION
**Pull request by conniec**
Issue: https://github.com/typelevel/cats/issues/1344

This is my first time contributing and am fairly new to these types so any feedback welcome. Would also like to add some examples if the code looks about right.

### CODE REVIEW

**Comment by non** [comment]
These seem good to me.

At a minimum we should have tests for both methods. It doesn't look like we have a tutorial for `EitherT` currently, but if we did have one adding these methods to it would be a good idea.

**Comment by travisbrown** [comment]
:+1:, looks good to me with the tests.

**Comment by peterneyens** [comment]
This looks good, thanks @conniec.

Maybe we can add the following example to `toNestedValidatedNel`, it shows the stereotypical example of error short circuiting versus error accumulation, but using `EitherT` and `Nested` / `ValidatedNel`. What do you think ?

```scala
import cats.data.{Nested, EitherT, ValidatedNel}
import cats.implicits._

type ErrorsOr[x] = ValidatedNel[String, x]
type OptionErrorsOr[x] = Nested[Option, ErrorsOr, x]

val ok = EitherT.right[Option, String, Int](Some(1))
val error = EitherT.left[Option, String, Int](Some("error"))

val okV: OptionErrorsOr[Int] = ok.toNestedValidatedNel
val errorV: OptionErrorsOr[Int] = error.toNestedValidatedNel

(okV |@| okV |@| okV).map(_ + _ + _)
// OptionErrorsOr[Int] = Nested(Some(Valid(3)))

(okV |@| errorV |@| errorV).map(_ + _ + _)
// OptionErrorsOr[Int] = Nested(Some(Invalid(NonEmptyList(error, error))))

(ok |@| error |@| error).map(_ + _ + _)
// EitherT[Option,String,Int] = EitherT(Some(Left(error)))
```

**Comment by travisbrown** [comment]
@peterneyens Maybe we should open an issue for `EitherT` documentation and update the `toNestedValidatedNel` example based on what ends up happening there? I'd be happy to see this merged as-is for now.

**Comment by peterneyens** [comment]
You're right, see #1425.

**Comment by conniec** [comment]
Thanks for the help everyone!

**Pull request merged**
