### PR TITLE
Experiment - seeing if this fixes builds

### PR DESCRIPTION
**Pull request by ceedubs**

### CODE REVIEW

**Comment by ceedubs** [comment]
🎉 @InTheNow's change fixed the build once it was moved to the existing `install` block in the travis configuration file.

**Comment by ceedubs** [comment]
I'm going to break procedure and go ahead and merge this, because I can't imagine anyone objecting to such a simple change that simultaneously fixes our builds and makes them no longer execute arbitrary code that comes back from a `curl` to a third party service.

**Comment by milessabin** [comment]
:+1:

**Comment by dwijnand** [comment]
Just as a side-note, food-for-thought: now it executes arbitrary code that comes back from `pip`...

**Comment by milessabin** [comment]
I agree that the `curl|bash` hate doing the rounds at the moment is a double standard, but still, this does fix the build as well ;-)

**Comment by ceedubs** [comment]
@dwijnand fair point :)

I think this is at least a slight improvement (beyond fixing the build). At one point when the build was failing it was because what we were feeding into `bash` was the HTML of a 500 Internal Server Error page. Hopefully `pip` at least handles server errors a bit more gracefully :)

**Pull request merged**
