### PR TITLE
Adds a script to try cats in ammonite

### PR DESCRIPTION
**Pull request by sisirkoppaka**
Based on try-shapeless

### CODE REVIEW

**Comment by non** [comment]
Seems good to me. 👍

**Comment by johnynek** [comment]
is there any way we can test that this is working in CI? Something like piping some input to it and then grepping the response might work. Things like this often bitrot because the core developers are not using it.

Also, if we add this, should we link to it in the readme and mention how it could be used (maybe with some horribly insecure curl pipe to bash?)

**Comment by sisirkoppaka** [comment]
Sure, I can do that. Good suggestion @johnynek

**Comment by kailuowang** [comment]
The fact that cats version is hardcoded here made me nervous. Trying cats in ammonite is actually quite easy 
```bash
brew install ammonite-repl
amm
```
then in ammonite-repl
```scala 
import $ivy.`org.typelevel::cats:0.7.2`, cats.implicits._

```
This is probably the quickist way to try cats in a repl. 
How about we just close this issue and add the above to the documentation (say FAQ? )

**Comment by milessabin** [comment]
What is this "brew" of which you speak? ;-)

**Comment by kailuowang** [comment]
@milessabin alright, this what @lihaoyi suggests
```
$ sudo curl -L -o /usr/local/bin/amm https://git.io/viYun && chmod +x /usr/local/bin/amm && amm
```

**Comment by milessabin** [comment]
You lost me a `sudo`.

**Comment by easel** [comment]
Looks like the preferred solution here is to document some preferred one-or-two-liners to the docs. Let's close out this PR in favor of that. Might not hurt to submit a PR to the ammonite docs as well.

**Comment by kailuowang** [comment]
Closing stale PRs. Feel free to reopen if there is interest to revive the effort.

**Pull request closed without merging**
