### PR TITLE
Remove blocking (JVM-only) Future instances

### LINKED ISSUE #589: jvm Future instances do not obey laws
Most of the type class instances in https://github.com/non/cats/blob/master/jvm/src/main/scala/cats/jvm/std/future.scala (`Comonad`, `Eq`, `PartialOrder`, `Order`) are not checked against their laws. If we were to check them against their laws they would fail, because they throw exceptions in the case of a failed future.

Furthermore, it isn't necessarily obvious how an `Eq[Future[A]]` instance should behave. The current one throws an exception if either `Future` fails. Consider the following scenario:

```scala
val fa: Future[Int] = Future.failed(new RuntimeException("foo"))

fa === fa
```

This last line throws an exception. One could reasonably expect it to return `true` instead. This does require creating an explicit `Eq` instance (with a supplied timeout), so it takes a little effort to get yourself into trouble. Still, I think that these instances belong in alleycats or tests but not in cats core. In addition to being unlawful, they aren't especially useful. Other than in tests, you probably always want to get back a `Future[Boolean]` when comparing two `Future[A]` values instead of blocking the thread waiting for both futures to complete.

### PR DESCRIPTION
**Pull request by ceedubs**
Fixes #589.

If anyone is set on using these, they can be added to alleycats.
However, I suspect that few to no people are using these. They all throw
exceptions on failed futures, which seems like it would be a
show-stopper in most codebases.

### CODE REVIEW

**Comment by adelbertc** [comment]
Build failure? But 👍

**Comment by ceedubs** [comment]
@adelbertc yeah, I don't completely understand the failure. The _build_ passed. The code coverage check is complaining. It seems that it doesn't know how to handle the fact that I removed a couple classes and their tests? I'm not sure.

**Comment by ceedubs** [comment]
I've resolved the merge conflict.

**Comment by non** [comment]
If no one object I'm fine with this. 👍

**Comment by adelbertc** [comment]
👍

**Comment by mpilquist** [comment]
👍

**Pull request merged**
