### PR TITLE
update bin compat versions to 1.0.0 and 1.1.0

### PR DESCRIPTION
**Pull request by kailuowang**
somehow I missed that last release

### CODE REVIEW

**Comment by tpolecat** [comment]
It should stay at 1.0 shouldn't it? We want to guarantee compatibility all the way back.

**Comment by kailuowang** [comment]
but that won't capture bin compat break between 1.1.0 and 1.2.0, e.g. if 1.1.0 introduced a new trait, 1.2.0 could add a method to it while still bin compat with 1.0.

**Comment by ChristopherDavenport** [comment]
@kailuowang  I believe MiMa allows multiple versions to be set. Such that mimaPreviousArtifacts points at both `1.1.0` and `1.0.0`

**Comment by kailuowang** [comment]
@chir thanks for the tip , I'll update that

**Comment by tpolecat** [comment]
I remain confused. What's the value in checking against 1.1.0?

**Comment by johnynek** [comment]
@tpolecat we could actually be compatible with `1.0.0` but not compatible with `1.1.0`. Imagine we remove some of the compatible methods we added in 1.1.0.

We want to be compatible with all previous versions in 1.x.y, and unless mima has bugs (which of course, it does because it is software), checking only the previous should be safe. But we could help detect bugs in mima by also doing the full transitive closure in our CI. If it gets too slow, we can only do a subset of the previous releases.

**Comment by tpolecat** [comment]
Aha, gotcha. Yep 👍

**Comment by tpolecat** [comment]
It would be cool if sbt-release maintained this list the same way it maintains `version`.

**Pull request merged**
