### PR TITLE
Use tut:book in invariantmonoidal doc

### PR DESCRIPTION
**Pull request by ceedubs**
To make it consistent with other docs.

### CODE REVIEW

**Comment by kailuowang** [comment]
usage of `std` package fails the build. My 👍  after build pass

**Comment by ceedubs** [comment]
@kailuowang I fixed the `std` issue in #1142 when I was merging in the changes from master. If we think that's good to go, then that should resolve this issue. Otherwise I can fix it separately and then resolve the conflicts in that PR.

**Comment by kailuowang** [comment]
Good deal, just gave my thumbs up on #1142

**Comment by OlivierBlanvillain** [comment]
:+1:

**Pull request merged**
