### PR TITLE
Bump base version to 2.10

### PR DESCRIPTION
**Pull request by armanbilge**

### CODE REVIEW

**Review by johnynek — APPROVED** [review]

**Comment by djspiewak** [comment]
Out of curiosity, why bump eagerly? Part of the original concept behind using base version is that you can wait to bump it until you actually add a source-breaking change.

**Comment by armanbilge** [comment]
@djspiewak right, same reasoning when we bumped to 2.9:
> Cats rarely release patches and we have a number of open PRs that would require a bump anyway. So bumping this pro-actively, and we can start a series/2.8 branch if anything crops up.

- https://github.com/typelevel/cats/pull/4239#issue-1274083479

**Comment by armanbilge** [comment]
At a glance 15/26 of the currently open PRs are source-breaking and would require a bump anyway.

**Comment by djspiewak** [comment]
Gotcha. Still feels slightly odd to do it here rather than bumping together with the change that actually breaks compatibility, but whatever works!

**Comment by armanbilge** [comment]
I agree :) what's missing is tooling support: if CI doesn't enforce the minor bump it is harder to enforce it.

**Pull request merged**
