### PR TITLE
Arrow Calculus With Documentation

### PR DESCRIPTION
**Pull request by LucDupAtGitHub**
removed app added docs

### CODE REVIEW

**Comment by LucDupAtGitHub** [comment]
folks, I chenged a bit of the Arrow.scala code that may be in conflict with other changes.

moreover I have to edit .gitignore to ignore elcipse project related files

**Comment by yilinwei** [comment]
The autogenerated `.class` files should probably be removed.

**Comment by ceedubs** [comment]
Hi @LucDupAtGitHub. Could you please provide a bit more information about this PR? There seem to be a lot of unrelated files checked in with it.

**Comment by easel** [comment]
This PR looks pretty stale, can we close it out?

**Comment by ceedubs** [comment]
Good call @easel. Closing out. @LucDupAtGitHub if you'd like to move forward with this, please open an issue with a description of the motivation for the changes. Thanks!

**Pull request closed without merging**
