### PR TITLE
Move Id instances into implicit scope for Scala 3

### PR DESCRIPTION
**Pull request by joroKr21**

### CODE REVIEW

**Review by johnynek — APPROVED** [review]

**Review by djspiewak — APPROVED** [review]

**Comment by joroKr21** [comment]
I think I missed `Semigroupal`

**Comment by armanbilge** [comment]
Ah, I was having trouble with this as well.

**Comment by armanbilge** [comment]
Btw, I think we also should consider putting `Id`'s implicits in its companion object.

**Comment by joroKr21** [comment]
It doesn't have a companion object - it's a type alias

**Comment by armanbilge** [comment]
Ok, well whatever you call the `object Id` that sits next to the type alias :) I'm pretty sure anything there is in implicit scope in Scala 3, I recently did this in https://github.com/typelevel/feral/pull/52/commits/744013e3ccd6123f0318f24f8fa3191b478aa919#diff-de6a1bd431e8326aa1f0db9116e7f8d27c15a9c8a6bb6344aec9984873eead98

**Comment by smarter** [comment]
For abstract types, scala 3 will look for implicits in the same-named object, but not for type alias if I'm not mistaken.

**Comment by armanbilge** [comment]
By abstract type, do you mean the difference between `type INothing <: Nothing` and `type INothing = Nothing`?

**Comment by smarter** [comment]
Yes.

**Comment by smarter** [comment]
Or well, types were the lower and upper bound actually differ, the `INothing <: Nothing` thing should in theory behave exactly like `INothing = Nothing` although the compiler implementation might not respect that

**Comment by armanbilge** [comment]
Well, FTR I just changed `INothing <: Nothing` to `INothing = Nothing` in that code I linked and it continues to grab the implicit from the `INothing` companion object.

**Pull request merged**
