### PR TITLE
Fix alleycats Set Functor ambiguous implicits

### PR DESCRIPTION
**Pull request by LaurenceWarne**
Hi, on `2.12.0` I find that I get the error: 

```
ambiguous implicit values:
  both value alleyCatsStdSetMonad in trait SetInstances of type cats.Monad[Set] with cats.Alternative[Set]
  and value alleyCatsSetTraverse in trait SetInstances of type cats.Traverse[Set]
  match expected type cats.Functor[Set] (lsp)
```

With for example the setup:

```scala
import alleycats.std.set._

object test {
  implicitly[cats.Functor[Set]]
}
```

To try and fix I've used the approach here: https://typelevel.org/cats/guidelines.html#implicit-instance-priority, which fixes the original problem though introduces binary compatibility issues which I don't know how to fix!:

```
[error]  * abstract synthetic method alleycats$std$SetInstances0$_setter_$alleyCatsStdSetMonad_=(cats.Monad)Unit in interface alleycats.std.SetInstances0 is inherited by class SetInstances in current version.
[error]    filter with: ProblemFilters.exclude[InheritedNewAbstractMethodProblem]("alleycats.std.SetInstances.alleycats$std$SetInstances0$_setter_$alleyCatsStdSetMonad_=")
[error]  * abstract synthetic method alleycats$std$SetInstances1$_setter_$alleyCatsSetTraverse_=(cats.Traverse)Unit in interface alleycats.std.SetInstances1 is inherited by class SetInstances in current version.
[error]    filter with: ProblemFilters.exclude[InheritedNewAbstractMethodProblem]("alleycats.std.SetInstances.alleycats$std$SetInstances1$_setter_$alleyCatsSetTraverse_=")
```

Suggestions very welcome! Thanks

### CODE REVIEW

**Comment by satorg** [comment]
@LaurenceWarne , thank you for your help!

Regarding the original issue:
> ambiguous implicit values:
  both value alleyCatsStdSetMonad in trait SetInstances of type cats.Monad[Set] with cats.Alternative[Set]
  and value alleyCatsSetTraverse in trait SetInstances of type cats.Traverse[Set]
  match expected type cats.Functor[Set] (lsp)

In theory, all these instances (i.e., `Traverse`, `Monad`, `Alternative`, etc) can be (and usually are) gathered in a single implementation class and therefore exposed by a single `implicit val`. For instance, see
https://github.com/typelevel/cats/blob/1cc04eca9f2bc934c869a7c5054b15f6702866fb/core/src/main/scala/cats/instances/list.scala#L36-L38

I'm not sure why in **alleycats** these instances were separated in the first place. Perhaps, it was just an oversight. I seems that if we merged them in just one implementor, then it would solve the issue. Perhaps, there were a reason to keep them separated, but I feel it may make sense to give it a shot and merge them. And if the effort fails for some reason, it would be nice to leave a comment about it in the sources, because for now it is not obvious at all.

Regarding the binary compatibility issue:
In the case when an `implicit val` is intentionally removed from a class or trait (and Mima apparently does not like it), the simplest way to overcome that is to remove implicit specifier from the `val` and furthermore make that `val` package-private. It should make Mima pretty happy.

**Comment by LaurenceWarne** [comment]
> In theory, all these instances (i.e., `Traverse`, `Monad`, `Alternative`, etc) can be (and usually are) gathered in a single implementation class and therefore exposed by a single `implicit val`. For instance, see
> 
> https://github.com/typelevel/cats/blob/1cc04eca9f2bc934c869a7c5054b15f6702866fb/core/src/main/scala/cats/instances/list.scala#L36-L38
> 
> I'm not sure why in **alleycats** these instances were separated in the first place. Perhaps, it was just an oversight. I seems that if we merged them in just one implementor, then it would solve the issue. Perhaps, there were a reason to keep them separated, but I feel it may make sense to give it a shot and merge them. And if the effort fails for some reason, it would be nice to leave a comment about it in the sources, because for now it is not obvious at all.

Makes sense, and FWIW moving all to one implementor doesn't appear to cause any test failures. 

> Regarding the binary compatibility issue: In the case when an `implicit val` is intentionally removed from a class or trait (and Mima apparently does not like it), the simplest way to overcome that is to remove implicit specifier from the `val` and furthermore make that `val` package-private. It should make Mima pretty happy. In other words, do not remove the `implicit val` physically, but rather un-implicit it and hide.

I may have misunderstood :sweat_smile: , but after moving to a common implementer and changing the old implicits:

```scala
trait SetInstances {
  private[std] val alleyCatsSetTraverse: Traverse[Set] = alleycatsStdInstancesForSet
  private[std] val alleyCatsStdSetMonad: Monad[Set] with Alternative[Set] = alleycatsStdInstancesForSet
  private[std] val alleyCatsSetTraverseFilter: TraverseFilter[Set] = alleycatsStdInstancesForSet

  implicit val alleycatsStdInstancesForSet
    : Monad[Set] with Alternative[Set] with Traverse[Set] with TraverseFilter[Set] = ...
```
I run into a few different mima issues:

```
[error]  * abstract synthetic method alleycats$std$SetInstances$_setter_$alleycatsStdInstancesForSet_=(cats.Monad)Unit in interface alleycats.std.SetInstances is present only in current version
[error]    filter with: ProblemFilters.exclude[ReversedMissingMethodProblem]("alleycats.std.SetInstances.alleycats$std$SetInstances$_setter_$alleycatsStdInstancesForSet_=")
[error]  * abstract method alleycatsStdInstancesForSet()cats.Monad in interface alleycats.std.SetInstances is present only in current version
[error]    filter with: ProblemFilters.exclude[ReversedMissingMethodProblem]("alleycats.std.SetInstances.alleycatsStdInstancesForSet")
[error]  * static method alleyCatsSetTraverseFilter()cats.TraverseFilter in class alleycats.std.all does not have a correspondent in current version
[error]    filter with: ProblemFilters.exclude[DirectMissingMethodProblem]("alleycats.std.all.alleyCatsSetTraverseFilter")
[error]  * static method alleyCatsSetTraverse()cats.Traverse in class alleycats.std.all does not have a correspondent in current version
[error]    filter with: ProblemFilters.exclude[DirectMissingMethodProblem]("alleycats.std.all.alleyCatsSetTraverse")
[error]  * static method alleyCatsStdSetMonad()cats.Monad in class alleycats.std.all does not have a correspondent in current version
[error]    filter with: ProblemFilters.exclude[DirectMissingMethodProblem]("alleycats.std.all.alleyCatsStdSetMonad")
[error]  * static method alleyCatsSetTraverseFilter()cats.TraverseFilter in class alleycats.std.set does not have a correspondent in current version
[error]    filter with: ProblemFilters.exclude[DirectMissingMethodProblem]("alleycats.std.set.alleyCatsSetTraverseFilter")
[error]  * static method alleyCatsSetTraverse()cats.Traverse in class alleycats.std.set does not have a correspondent in current version
[error]    filter with: ProblemFilters.exclude[DirectMissingMethodProblem]("alleycats.std.set.alleyCatsSetTraverse")
[error]  * static method alleyCatsStdSetMonad()cats.Monad in class alleycats.std.set does not have a correspondent in current version
[error]    filter with: ProblemFilters.exclude[DirectMissingMethodProblem]("alleycats.std.set.alleyCatsStdSetMonad")
```

**Comment by satorg** [comment]
Ah, that's right – Mima gets triggered if you change visibility from public to package-private. I misguided you, sorry. Now I'm recalling that in cases like this one the approach is usually not to change the visibility but rather  mark it `@deprecated` (along with stripping off all `implicit` whatever), e.g.:
https://github.com/typelevel/cats/blob/1cc04eca9f2bc934c869a7c5054b15f6702866fb/kernel/src/main/scala/cats/kernel/instances/SortedMapInstances.scala#L51-L53

**Comment by satorg** [comment]
Note, that it is not necessary to merge the `TraverseFilter` instance with all the others because it has no base type class in common. So technically, you can keep it separated as before. On the other hand I guess it won't hurt if you merge them, probably.

**Comment by satorg** [comment]
Hmm.. Even without Mima the statement like
```
val alleyCatsSetTraverse: Traverse[Set] = alleycatsStdInstancesForSet
```
where `alleycatsStdInstancesForSet` is `val` and defined down below in the trait
won't work
because it leads to the forward reference issue.
Perhaps, Mima tries to tell just about that but in its own way.

On the other hand, using `implicit def` is not exactly very optimal because it will result in reallocating a new instance every time it is demanded. Certainly, there are some cases where `implicit def` cannot be avoided, but as a rule of thumb Cats attempts to keep the number of allocations as minimal as possible.

Would you give it a shot and make `implicit val alleycatsStdInstancesForSet` again and move it _before_ any dependent declaration occurs in the trait please?

**Comment by LaurenceWarne** [comment]
I pushed it up if you wanted to take a look @satorg :slightly_smiling_face:

**Comment by satorg** [comment]
@LaurenceWarne ,
it was quite tricky, but looks like I managed to overcome it:
https://github.com/typelevel/cats/commit/a7c7ce18aba68de5f615c6d9cf04c31d6f956a7a

Looks like moving the instance value into a companion object somehow resolves the compatibility conundrum (or maybe just makes Mima believing it).

Feel free to take this commit and adjust it accordingly, if necessary.
Hopefully, it works as expected.

**Comment by satorg** [comment]
Tests failed on ubuntu-latest, 2.13, temurin@17, catsJVM:
```
2024-12-04T18:13:57.2635351Z ==> X cats.jvm.tests.FutureSuite.Future: coflatMap.coflatten throughMap  3.012s munit.FailException: Failing seed: 2fAhXEoX8givw6BzXBkSKZe_3YtAuY5ouy7u7RWMA2B=
2024-12-04T18:13:57.2636731Z You can reproduce this failure by adding the following override to your suite:
2024-12-04T18:13:57.2637201Z 
2024-12-04T18:13:57.2637592Z   override def scalaCheckInitialSeed = "2fAhXEoX8givw6BzXBkSKZe_3YtAuY5ouy7u7RWMA2B="
2024-12-04T18:13:57.2638137Z 
2024-12-04T18:13:57.2638326Z Exception raised on property evaluation.
2024-12-04T18:13:57.2638860Z > ARG_0: Future(Failure(java.lang.Exception))
2024-12-04T18:13:57.2639612Z > Exception: java.util.concurrent.TimeoutException: Future timed out after [3 seconds]
2024-12-04T18:13:57.2640866Z     at munit.ScalaCheckSuite.propToTry(ScalaCheckSuite.scala:98)
2024-12-04T18:13:57.2642215Z Caused by: java.util.concurrent.TimeoutException: Future timed out after [3 seconds]
2024-12-04T18:13:57.2643573Z     at scala.concurrent.impl.Promise$DefaultPromise.tryAwait0(Promise.scala:248)
2024-12-04T18:13:57.2645051Z     at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:261)
2024-12-04T18:13:57.2646421Z     at scala.concurrent.Await$.$anonfun$result$1(package.scala:201)
2024-12-04T18:13:57.2647838Z     at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:62)
2024-12-04T18:13:57.2649135Z     at scala.concurrent.Await$.result(package.scala:124)
2024-12-04T18:13:57.2650849Z     at cats.jvm.tests.FutureSuite.cats$jvm$tests$FutureSuite$$$anonfun$eqfa$1(FutureSuite.scala:45)
```

But it doesn't look related to the PR. Perhaps, some flakiness of the `FutureSuite`.

**Review by satorg — APPROVED** [review]
Looks good to me, thanks!

**Comment by satorg** [comment]
@LaurenceWarne , it looks like your PR got conflicts due to recent merges to the main branch. Sorry for that 🤷  Would you be open to resolve the conflicts to make your PR mergeable (since otherwise it looks pretty good to go). Thank you!

**Comment by LaurenceWarne** [comment]
Sure, done!

**Review by satorg — APPROVED** [review]
Thank you!

**Review by kubukoz — APPROVED** [review]

**Pull request merged**
