### PR TITLE
Replace List with Chain in Validated's docs

### PR DESCRIPTION
**Pull request by satansk**
* `ValidatedNel` to `ValidatedNec`
* `NonEmptyList` to `NonEmptyChain`
* `List` to `Chain`

### CODE REVIEW

**Comment by LukaJCB** [comment]
This is great, thanks!
It still seems to run into some errors with `tut` though, it'd be great if you could fix those :)

**Comment by satansk** [comment]
Hi @LukaJCB , the reason for the `tut` errors is the missing `toValidatedNec` method of `Validated`, there's a `toValidatedNel` in it.

So should I add `toValidatedNec` to `Validated`, or what else I can do to avoid the errors?

Thanks :)

**Comment by LukaJCB** [comment]
Can you merge this with master now that #2487 is merged? :)

**Comment by kailuowang** [comment]
Thank you!

**Pull request merged**
