### PR TITLE
Add leftFlatMap to Either

### PR DESCRIPTION
**Pull request by rohanshah**
### Motivation

`Either` should have `leftFlatMap` for cases when you want to `leftMap` a function that returns an `Either` and flatten the total result.

### CODE REVIEW

**Comment by kailuowang** [comment]
would love to see some tests

**Comment by rohanshah** [comment]
@kailuowang yeah, I was wondering where to put them. The only test file I found for `Either` was [EitherSuite.scala](https://github.com/typelevel/cats/blob/master/tests/src/test/scala/cats/tests/EitherSuite.scala) but that didn't even have a test for `flatMap` in it.

**Comment by kailuowang** [comment]
EitherSuite should be the right place. My guess is that `flatMap` isn't explicitly tested there because  it's covered by the law tests

**Comment by rohanshah** [comment]
@kailuowang added tests!

**Pull request merged**
