### PR TITLE
add trailing slashes to URLs

### PR DESCRIPTION
**Pull request by larsrh**
This is required for migration to HTTPS (see typelevel/general#75).

Would be great if someone could merge this & update the site.

### CODE REVIEW

**Comment by larsrh** [comment]
@kailuowang Would be great if you could re-generate pages too.

**Comment by kailuowang** [comment]
@larsrh will do soon once I merge all the doc PRs I can merge today.

**Comment by larsrh** [comment]
Thanks :+1:

**Comment by kailuowang** [comment]
@larsrh published.

**Pull request merged**
