### PR TITLE
Adding WriterT Monoid

### PR DESCRIPTION
**Pull request by yilinwei**
Adding WriterT Monoid as referenced in #1012. 

It's also come to my attention that it's one of the subtasks in #620.

### CODE REVIEW

**Comment by yilinwei** [comment]
After using in our application code further I'm seeing similar behaviour that @ceedubs is seeing for `MonadError` in #689.

In particular I seem to have some trouble resolving the `Monoid` which should exist for `Id` and `Xor` as the `F[_]`. The kinds with a 'normal' `F[_]` shape (apart from `Id`) such as `Option` and `List` seem to work well.

```
  //explicit call works, implicitly fails, resolve fails
  writerTMonoid[String Xor ?, String, Unit]
  implicitly[Monoid[WriterT[String Xor ?, String, Unit]]]
  resolveMonoid[WriterT[String Xor ?, String, ?]]

  //implicitly and resolve both work
  implicitly[Monoid[WriterT[List, String, Unit]]]
  resolveMonoid[WriterT[List, String, ?]]

  //implicitly works, and resolve fails
  implicitly[Monoid[WriterT[Id, String, Unit]]]
  resolveMonoid[WriterT[Id, String, ?]]

  //implicitly and resolve both work
  implicitly[Monoid[WriterT[Option, String, Unit]]]
  resolveMonoid[WriterT[Option, String, ?]]
```

**Comment by yilinwei** [comment]
I've checked in `scalaz` and can see the same issue with their `WriterT` implementation with `\/` and `Id`. Also, the semigroup `|+|` works with `Id` as `F[_]` but not `Xor` which I guess is vaguely expected since `implicitly` works for `Id` but not `Xor`.

**Comment by adelbertc** [comment]
Is this SI-2712?

**Comment by yilinwei** [comment]
I compiled against @milessabin proposed fix for SI-2712 and it didn't work.

A simplified repro,

```
trait TC[A]
trait Foo[A, B]
trait Bar[F[_], A]

object Check {
  implicit val a: TC[Unit] = ???
  implicit def fooTC[A, B](implicit a: TC[A]): TC[Foo[A, B]] = ???
  implicit def barTC[F[_], A](implicit fa: TC[F[A]]): TC[Bar[F, A]] = ???
  
  //works
  implicitly[TC[Foo[Unit, Unit]]]
  //doesn't work
  implicitly[TC[Bar[({type L[A] = Foo[Unit, A]})#L, Unit]]]
  //works
  barTC[({type L[A] = Foo[Unit, A]})#L, Unit]
}


```

**Comment by ceedubs** [comment]
@yilinwei thanks a lot for getting the ball rolling on this and identifying implicit resolution issues!

I've submitted a PR to your branch that helps with the case of `Id`. If you merge it, then the updates should appear on this PR.

I'm not sure what to do about the `Xor` case. We might just have to punt on it for now.

**Comment by yilinwei** [comment]
I think we can leave the Xor use case for now - I'm not really familiar with codecov.io - what does the check mean and is there anything I should be doing?

**Comment by ceedubs** [comment]
👍 lgtm. I don't entirely understand what's going on with the code coverage report. I think something weird is happening because of the separation of the `free` module that has been merged to master. I wouldn't worry about it too much.

**Comment by adelbertc** [comment]
👍

**Pull request merged**
