### PR TITLE
#resolves 2715 add minimumoption and maximumoption to unorderedfoldable

### PR DESCRIPTION
**Pull request by mschuwalow**
Thank you for contributing to Cats!

This is a kind reminder to run `sbt prePR` and commit the changed files, if any, before submitting.

### CODE REVIEW

**Comment by kailuowang** [comment]
Is this urgent? if not can we wait on adding them directly to the type class once 2.0 is released?

**Comment by mschuwalow** [comment]
> Is this urgent? if not, can we wait a bit so that we can add them directly to the type class once 2.0 is released?

Sure we can do that. Just comment here once this becomes relevant and I'll update the pr

**Comment by travisbrown** [comment]
@mschuwalow Would you want to revisit this now that 2.0 is out and the `BinCompat` trait isn't necessary?

**Comment by mschuwalow** [comment]
Sure, I'll try to update the pr this week

**Comment by LukaJCB** [comment]
Hey @mschuwalow, did you close this on purpose? :) 
If you no longer want to update the PR do you mind if someone else goes for it?

**Pull request closed without merging**
