### PR TITLE
Fix typo in SemigroupK scaladoc

### PR DESCRIPTION
**Pull request by LukaJCB**

### CODE REVIEW

**Comment by kailuowang** [comment]
not a native speaker, but according to dictionary, both valid spelling of the word?

**Comment by johnynek** [comment]
seems both are legit, but this change moves to the more common usage on mathscinet (but only a 2 to 1 ratio):

https://english.stackexchange.com/questions/79847/parametrise-or-parameterise-a-curve

fine with me to make the change.

👍

**Comment by fthomas** [comment]
If we do this, we should change all occurrences of "parameterized":
https://github.com/typelevel/cats/search?utf8=%E2%9C%93&q=parameterized

**Comment by LukaJCB** [comment]
Huh, didn't know both versions are valid, TIL 😄 
I'll go ahead and change the other occurrences

**Comment by johnynek** [comment]
👍

**Pull request merged**
