### PR TITLE
Get ready for RC2

### PR DESCRIPTION
**Pull request by LukaJCB**
We're really close to 1.0, so I decided to draft some release notes. I think it'd be great if we could also get a blog post on typelevel.org in time as well. :)

Only have a couple of tickets still open:

- [x] standardise on `liftF` and add `liftK` to transformers #2033
- [x] Add ContravariantMonoidal #2034

And then we have a couple of others that break bincompat so we should think about including them in 1.0.0

- [x] Add distributive typeclass and some instances #2046

### CODE REVIEW

**Comment by kailuowang** [comment]
Awesome @LukaJCB. I can draft the blog post unless you want to. I am thinking of giving a quick overview how we get here and our commitment to compatibility and community building going forward.

**Comment by LukaJCB** [comment]
If you draft the blog post, that'd be absolutely great! Im sure we could collaborate to create a really good one!

**Comment by kailuowang** [comment]
great I'll start draft one tomorrow.

**Comment by kailuowang** [comment]
Do you want to also update the AUTHORS.md? Or I'll be happy to do that.

**Comment by LukaJCB** [comment]
Sure thing, will do! Is there a good way to find out who's a new contributor, or do I have to do it manually? :)

**Comment by kailuowang** [comment]
I used some scala code to do that one time, and the next time I lost that code so I did manual. Not much difference in terms of time consumed.

**Comment by LukaJCB** [comment]
Alright then 😁 I've also written up something for the blog post, will you create a PR to the Typelevel blog, or should I do that?

**Comment by kailuowang** [comment]
I am also drafting. I'd say you create a PR here (mark as DO NOT MERGE) before we submit to typelevel blog?

**Comment by kailuowang** [comment]
also are we determined to wait for  #2046?

**Comment by LukaJCB** [comment]
I think we should wait for it, yeah. If needs be, I can get it done on the weekend :)

**Comment by kailuowang** [comment]
how about #2056, #2057, they are not super essential but I think they are easy and quick to be incorporated. On the other hand we might need to quickly cut the release after them before letting more PRs like these to drag us on.

**Comment by LukaJCB** [comment]
I'd say we set the deadline for these kinds of PRs for Monday. WDYT? :)

**Pull request merged**
