### PR TITLE
Make the value of the class private

### LINKED ISSUE #2514: Value classes' public `val` field introduce unnecessary collisions
In Scala 2.10 the underlying value field in a value class has to be public, 
For example 
```scala
final class EitherIdOpsBinCompat0[A](val value: A) extends AnyVal
```
In this particular case, it introduced a `value` val to all types that simply returns itself. There is no real use case for this it's only due to the limitation of value classes in 2.10. It collides with any implicit extension that adds a `value` too. See https://github.com/typelevel/cats/issues/2491 for detail in this case. 
This limitation is removed since Scala 2.11. And Cats dropped support for 2.10 since 1.3. 

I thought of two approaches that can fix this. 

Option 1: make the existing [implicit conversion](https://github.com/typelevel/cats/blob/master/core/src/main/scala/cats/syntax/either.scala#L382-L383) and [value class `EitherIdOpsBinCompat0`](https://github.com/typelevel/cats/blob/master/core/src/main/scala/cats/syntax/either.scala#L386) package private and deprecated; copy the value class `EitherIdOpsBinCompat0` and paste it as a new value class with its `value` private and new implicit conversion for it. We also need a new `EitherSyntaxBinCompat1` trait for maintaining BC on Scala 2.11. 
I believe that this would be binary compatible and hide the `value` field going forward, but I haven't tested it yet. The downside is, of course, the duplicated code and more boilerplate. Also if we want to use the syntax inside the package we will run into collision.  

Option 2:  make the `value` field private. It seems to me that unless user calls the `value` field which has no practical usage, user won't run into binary compatibility issue. This can be verified by adding a `"232". leftNec[Int]` line to the [BC test](https://github.com/typelevel/cats/blob/3bb271406619434ba29fd31219ee8b98ef425f06/binCompactTest/src/main/scala/catsBC/MimaExceptions.scala#L8) added by #2509 ~(not merged yet)~ . We would also need to add a MiMa exception for this field. 

What do you guys think?

### PR DESCRIPTION
**Pull request by coltfred**
This makes the `.value` of two of the `Ops` classes private, since they shouldn't ever be referenced and they collide with Scalatest.

Fixes #2514 and #2613

### CODE REVIEW

**Comment by kailuowang** [comment]
Thanks! Would you also add usages of the syntax to https://github.com/typelevel/cats/blob/master/binCompatTest/src/main/scala/catsBC/MimaExceptions.scala
something like 
`"blah".leftNec[Int]`

This will make sure that such usages are still binary compatible.

**Comment by kailuowang** [comment]
once this approach is approved, I'd like to update *all* value classes fields to private in Cats

**Comment by coltfred** [comment]
@kailuowang Added.

**Comment by coltfred** [comment]
I think I've proven to myself that things still work as expected, so this should be ready for actual review.

**Comment by kailuowang** [comment]
Thanks @coltfred

**Comment by kailuowang** [comment]
@rossabaker @ceedubs @LukaJCB what do you think of this? 
This is mostly to fix to the public field of value classes causing conflicts with other extensions. We had to make them public due to restrictions on scala 2.10 but we already dropped 2.10 support. If you all agree with this approach, I am going to create an issue to make **all*** value class fields private.

**Comment by LukaJCB** [comment]
This looks very reasonable, If everything still works as is then I'm happy to change this for all the extensions. Are we going to do an 1.5.0-RC1? We could make sure everything still works with that release :)

**Comment by kailuowang** [comment]
@LukaJCB yes I think we should do a RC1

**Comment by coltfred** [comment]
I'm more than happy to give a 1.5.0-RC1 a try today or this weekend.

**Pull request merged**
