### PR TITLE
Minimizing typeclass surface in cats-kernel

### PR DESCRIPTION
**Pull request by denisrosset**
As per #1995

### CODE REVIEW

**Comment by LukaJCB** [comment]
Can you rebase with master? :)

**Comment by kailuowang** [comment]
this wil fail Mima test , need to add some exceptions [here](https://github.com/typelevel/cats/blob/master/build.sbt#L236)

**Comment by kailuowang** [comment]
> [info] Compiling 78 Scala sources to /home/travis/build/typelevel/cats/tests/.js/target/scala-2.11/test-classes...
[error] /home/travis/build/typelevel/cats/tests/src/test/scala/cats/tests/SortedSetSuite.scala:17: value reverse is not a member of cats.kernel.PartialOrder[scala.collection.immutable.SortedSet[Int]]
[error]   checkAll("PartialOrder[SortedSet[Int]].reverse", PartialOrderTests(PartialOrder[SortedSet[Int]].reverse).partialOrder)
[error]                                                                                                   ^
[error] /home/travis/build/typelevel/cats/tests/src/test/scala/cats/tests/SortedSetSuite.scala:18: value reverse is not a member of cats.kernel.PartialOrder[scala.collection.immutable.SortedSet[Int]]
[error]   checkAll("PartialOrder[SortedSet[Int]].reverse.reverse", PartialOrderTests(PartialOrder[SortedSet[Int]].reverse.reverse).partialOrder)
[error]                                                                                                           ^
[error] two errors found
[error] (testsJS/test:compileIncremental) Compilation failed

**Comment by denisrosset** [comment]
@kailuowang Rebased with the latest master, should solve the SortedSetSuite problem.

PS: my git-fu is minimal, how should I combine the above commits to avoid polluting the history?

**Comment by denisrosset** [comment]
We should also remove the tests corresponding to the old `.reverse.reverse` test, as we no longer perform the optimization that the reverse of the reverse is the original object.

Note: I could restore this optimization by pattern matching on the type of derived `Order`, at the price of adding new classes.

**Comment by kailuowang** [comment]
Its okay to have multiple trivial commits in a PR. We will squash merge into one commit. I myself don't see it necessary to optimize .reverse.reverse. Testing it against the law doesn't hurt though right?

**Comment by denisrosset** [comment]
It doesn't hurt, but it's unnecessary, as the `.reverse.reverse` test was covering an optimization that is no longer there, so we are basically testing that `-(-x) = x` as the `Order.reverse` method cannot be overloaded. Your call.

**Pull request merged**
