### PR TITLE
Updates for 2.13.0-RC2

### PR DESCRIPTION
**Pull request by travisbrown**
Depends on a new Discipline release with [this change](https://github.com/typelevel/discipline/pull/98) and Machinist but otherwise I think this is ready to go.

### CODE REVIEW

**Comment by kailuowang** [comment]
thanks to #2858 by @dotta, merging in master should probably fix the build here

**Comment by travisbrown** [comment]
We’ll still need Machinist and Discipline releases but thanks!

**Comment by travisbrown** [comment]
Just confirmed that `+buildJVM` is fine here with the current Discipline master locally published as 0.12.0 (thanks for the Machinist release, @larsrh).

**Comment by larsrh** [comment]
I've fixed the Discipline build number. Now, waiting for tut.

**Comment by larsrh** [comment]
tpolecat/tut#250

**Comment by travisbrown** [comment]
Thanks @larsrh! I’m going to be away from the computer until next Wednesday so anyone should feel free to grab these commits or whatever.

**Comment by larsrh** [comment]
Turns out we don't necessarily need `tut` because CI runs it only on 2.12.

**Comment by kailuowang** [comment]
I am out of town this weekend. If no one beats me, I can cut a cats 2.0m2 release Tuesday

**Comment by travisbrown** [comment]
Excellent, thanks all!

**Comment by rossabaker** [comment]
I'm around tonight.  Is [releasing](https://github.com/typelevel/cats/blob/master/PROCESS.md#releasing) still the state of the art?

**Pull request merged**
