### PR TITLE
Add Align lawful tests for Option instance

### PR DESCRIPTION
**Pull request by gagandeepkalra**
while back-porting `Align` to Scala 2.11, noticed we are missing tests for `Option` instance.

### CODE REVIEW

**Comment by travisbrown** [comment]
Can you rebase or merge master and add the import? Thanks for catching this!

**Comment by travisbrown** [comment]
I think it still needs the `cats.Align` import (we recently changed the tests to use imports instead of package nesting in order to match usage more directly).

**Comment by gagandeepkalra** [comment]
Sorry, I did that in a hurry.

**Comment by gagandeepkalra** [comment]
Thank you, Sir 🙂

**Pull request merged**
