### PR TITLE
Add an explanation for the missing Applicative instances for monad transformers

### LINKED ISSUE #2272: Document why monad transformers don't have Applicative instances.
see https://github.com/typelevel/cats/pull/2181#issuecomment-370098157
Probably in the FAQ section, maybe also mention in the guideline.

### PR DESCRIPTION
**Pull request by kubukoz**
Closes #2272.

Just a few lines to start with, hope you have some feedback on what else I can mention/what can be reworded :)

### CODE REVIEW

**Comment by LukaJCB** [comment]
I like it, but can we extract a bit from the issue you linked, I feel like just linking to an issue will cause people to have to wade through a bunch of discussion instead of getting to the actual point. You know what I mean? 🤔

**Comment by kubukoz** [comment]
Sure, I'll look for something that can be there instead of the link.

**Comment by kubukoz** [comment]
Can we just drop the link? The potential inconsistency is already mentioned. WDYT?

**Comment by LukaJCB** [comment]
I think that might be more confusing, then it'd just say "This is inconsistent" without naming a good reason.

**Comment by LukaJCB** [comment]
Maybe add the counter example noted here? https://github.com/typelevel/cats/pull/1106#issuecomment-225067111

Of course would need porting to `EitherT` or `OptionT` instead. :)

**Comment by kubukoz** [comment]
@easel I haven't had much time to work on this recently, but I'll surely extract something before I consider this good to merge :P

**Comment by kubukoz** [comment]
@LukaJCB as part of this week's goal to finish up all open OSS PRs, I updated this one - please take a look :)

**Comment by kubukoz** [comment]
@kailuowang FYI

**Comment by kailuowang** [comment]
Thanks very much @kubukoz !

**Pull request merged**
