### PR TITLE
Adds version of mkString_ with no prefix/suffix, matching the std lib.

### PR DESCRIPTION
**Pull request by matthughes**
Thank you for contributing to Cats!

This is a kind reminder to run `sbt prePR` and commit the changed files, if any, before submitting.

### CODE REVIEW

**Comment by matthughes** [comment]
Fixes #2663 but as it stands, this is going to fail binary compatibility rules.  Not sure how best to get around?  I could change the name but I got no suggestions.

**Comment by kailuowang** [comment]
I am not sure if this is going to break binary compatibility. Right now the build break due to format issue, a `sbt prePR` will format the code and also check if it breaks binary compatibility.

**Comment by kailuowang** [comment]
@matthughes thanks!
The short answer is: yes, please move it `FoldableOps0` and I'd perfer call `new FoldableOps(f).mkString_("", delim, "")`

The longer answer: 
ah, it looks like adding an override to a method also breaks BC. Good to learn something new.  
`FoldableOps0` and ``FoldableOps1` were created recently to get around binary incompatibility. Mima is happy when you move the method to `FoldableOps0` because that one is not officially released yet, it's released on 1.6.0-RC1, and mima doesn't check BC against RC releases. If we can make this one in 1.6.0 we should be good. Just noticed that your PR is against 1.6.x branch rather than master, so we are good on that as well.

**Comment by mpilquist** [comment]
Note: adding an overload to a regular class doesn't break binary compat but doing so to a value class does. The existence of an overload changes the scheme used for generation of the synthetic method names in the companion class.

Consider these two classes, representing 2 different versions of the same class:

```scala
class Foo1(val x: Int) extends AnyVal {
  def foo(y: Int): Int = x + y
}

class Foo2(val x: Int) extends AnyVal {
  def foo(y: Int): Int = x + y
  def foo(y: Int, z: Int): Int = x + y + z
}
```

`Foo1.class` and `Foo2.class` are binary compatible (modulo the class name difference of Foo1 vs Foo2). However, `Foo1$.class` and `Foo2$.class` are not.

`Foo1$.class` has this method:
```
  public final int foo$extension(int, int);
    descriptor: (II)I
    flags: ACC_PUBLIC, ACC_FINAL
```

`Foo2$.class` has these methods:
```
  public final int foo$extension0(int, int);
    descriptor: (II)I
    flags: ACC_PUBLIC, ACC_FINAL
<snip>

  public final int foo$extension1(int, int, int);
    descriptor: (III)I
    flags: ACC_PUBLIC, ACC_FINAL
```

**Comment by kailuowang** [comment]
@mpilquist ah, that makes sense, thanks for the detail! In hindsight, maybe the first one should've been made `foo$extension0` rather than `foo$extension`. I'll see if I can find an existing scalac issue for this one.

**Comment by kailuowang** [comment]
@matthughes I updated the CatsSuite which is missing the newly added syntax trait and caused the broken build. Hopefully this one will be ready to merge soon.

**Pull request merged**
