### PR TITLE
skip javadoc compilation for 2.10

### PR DESCRIPTION
**Pull request by kailuowang**
Hopefully this would unblock #898 and #1041

### CODE REVIEW

**Comment by ceedubs** [comment]
Thanks @kailuowang - I'm glad to hopefully see the end of the doc troubles. Would you mind adding a brief comment about why this is being done?

**Comment by kailuowang** [comment]
@ceedubs just consolidated with the existing skip-doc-at-210 settings together with its comment.

**Comment by ceedubs** [comment]
👍

**Comment by kailuowang** [comment]
per conversation with @InTheNow at gitter, we might be able find a better solution than this. Javadoc generation is probably fine with sbt 0.13.11 (turned on `-Ymacro-no-expand` by default). It's the makeSite that fails for laws

**Comment by non** [comment]
Yeah, this makes sense. We should open an issue to re-enable these once @InTheNow's fixes land in SBT. 👍

**Pull request merged**
