### PR TITLE
added instance table to docs, enhanced typeclass diagram

### PR DESCRIPTION
**Pull request by kailuowang**
UPDATE: I switched to tpolecat's infographic. ~~But Don't merge yet, it seems to me that microsites doesn't support .svg files, see https://github.com/47deg/sbt-microsites/issues/182~~
SVG issue resolved ready to review/merge. 
Originally from [@alexknvl](https://gist.github.com/alexknvl/d63508ddb6a728015ace53cb70a1fd5d)
The instance table

| Type            | Functor | Apply             | Applicative | Monad | MonoidK | ApplicativeError  | MonadError | CoflatMap | Comonad |
| --------------- |:-------:|:-----------------:|:-----------:|:-----:|:-------:|:-----------------:|:----------:|:---------:|:-------:|
| Id[A]           | ✔       | ✔                 | ✔           | ✔     | ✗       | ✗                 | ✗          | ✔         | ✔       |
| Eval[A]         | ✔       | ✔                 | ✔           | ✔     | ✗       | ✔                 | ✔          | ✔         | ✔       |
| Option[A]       | ✔       | ✔                 | ✔           | ✔     | ✔       | ✗                 | ✗          | ✔         | ✗       |
| Const[K, A]     | ✔       | ✔ (`K:Monoid`)    | ✔           | ✗     | ✗       | ✗                 | ✗          | ✗         | ✗       |
| Either[E, A]    | ✔       | ✔                 | ✔           | ✔     | ✔       | ✔                 | ✔          | ✗         | ✗       |
| List[A]         | ✔       | ✔                 | ✔           | ✔     | ✔       | ✗                 | ✗          | ✔         | ✗       |
| NonEmptyList[A] | ✔       | ✔                 | ✔           | ✗     | ✗       | ✗                 | ✗          | ✔         | ✔       |
| Stream[A]       | ✔       | ✔                 | ✔           | ✔     | ✔       | ✗                 | ✗          | ✔         | ✗       |
| Map[K, A]       | ✔       | ✔                 | ✗           | ✗     | ✔       | ✗                 | ✗          | ✗         | ✗       |
| Validated[E, A] | ✔       | ✔ (`E: Semigroup`)| ✔           | ✗     | ✗       | ✔ (`E: Semigroup`)| ✗          | ✗         | ✗       |
| Reader[E, A]    | ✔       | ✔                 | ✔           | ✔     | ✗       | ✗                 | ✗          | ✗         | ✗       |
| Writer[E, A]    | ✔       | ✔ (`E:Monoid`)    | ✔           | ✔     | ✗       | ✗                 | ✗          | ✔         | ✗       |

The typeclass infograph from [@tpolecat](https://github.com/tpolecat/cats-infographic/blob/master/cats.pdf)

### CODE REVIEW

**Comment by peterneyens** [comment]
This sort of solves #1287.

**Comment by juanpedromoreno** [comment]
@kailuowang Regarding the svg issue, I think the problem might be related to Jekyll filtering:

Could you please try to put below this [line](https://github.com/typelevel/cats/blob/master/build.sbt#L162) the next sbt config? 

```scala
includeFilter in Jekyll := "*.html" | "*.css" | "*.png" | "*.jpg" | "*.gif" | "*.js" | "*.swf" | "*.yml" | "*.md" | "*.svg"
```

The trick would be using `Jekyll` scope (you might even combine the same includeFilter for both makeSite and Jekyll scopes).

Let me know if that solves the issue.

**Comment by kailuowang** [comment]
@juanpedromoreno that indeed fixed the issue. Thanks very much!

**Comment by djspiewak** [comment]
@tpolecat The graph is amazing, though unfortunately it's a bit out of date on the cats-effect front since we had to make `Async <: Sync` directly, rather than sitting in parallel.

**Comment by tpolecat** [comment]
@kailuowang is it possible to link directly to the SVG in my repo so it gets updated automatically?

**Comment by kailuowang** [comment]
@tpolecat it's certainly desirable from my point of view. In fact, that's the first thing I tried. I couldn't find a url of it that points to the latest version and with the right content type.  Maybe you have to publish it to gh-pages? (or just make gh-pages your main branch?)

**Comment by tpolecat** [comment]
The internet showed me this trick but I don't know if it's a reasonable long-term solution. Below the link is:

    https://cdn.rawgit.com/tpolecat/cats-infographic/master/cats.svg

The embedded png file isn't showing up but I'm not sure what to do about that. I could just remove it, it doesn't really add anything.

**Comment by johnynek** [comment]
NonEmptyList is a monad, no?
https://github.com/typelevel/cats/blob/master/core/src/main/scala/cats/data/NonEmptyList.scala#L368

**Comment by kailuowang** [comment]
@tpolecat awesome! Just updated. I think a midterm solution is good enough for now.

**Comment by kailuowang** [comment]
@johnynek good catch, fixed.

**Comment by tpolecat** [comment]
@kailuowang I updated the infographic but it's not showing up on the cdn yet. It may be cached for a while.

**Comment by kailuowang** [comment]
ping @johnynek. Do yo have time to take another look?

**Pull request merged**
