### PR TITLE
Validated doctest

### PR DESCRIPTION
**Pull request by hamednourhani**
Re: Issue #2479

Add more doctest to Validated methods:

- fold
- isValid
- isInvalid
- forearch
- getOrElse
- valueOr
- exists
- forall
- orElse
- findValid
- toEither
- toOption
- toIor
- toList
- toValidatedNel
- toValidatedNec
- withEither
- bimap
- compare
- ===
- ap
- product
- map
- leftMap
- traverse
- foldLeft
- foldRight
- andThen
- combine
- swap
- merge

### CODE REVIEW

**Comment by hamednourhani** [comment]
@kailuowang can i know about the review process . also the process of adding pull requests to millstone. Thanks a lot. :)

**Comment by kailuowang** [comment]
@hamednourhani I don't think we have formal process of PR review other than it usually requires 2 maintainer approvals before it can be merged. Cats maintainers are volunteers using their spare time for this endeavor. (we have a [sustainability program](https://donorbox.org/typelevel-sustainability-program-2019) that as of now it still lack enough funding to hire even one part-time maintainer.) As a result, the speed of PR reviewing is not very predictable. Sometimes pinging maintainers in the PR or soliciting review in cats' gitter chatters move things forward, as I myself have done countless times in the past. 
Milestone assignments is mostly done by individual maintainers, the bulk of which happens during a release, when all unassigned merged PR will be assigned to the milestone representing the upcoming release. There are also PRs that maintainers have specific reasons to assign to certain milestones. Anyone can suggest a milestone assignment, but usually it's not necessary.  

I hope that answers your question.

**Comment by hamednourhani** [comment]
Thanks a lot @kailuowang for you reply.

**Comment by hamednourhani** [comment]
@LukaJCB would you please review this PR.

**Comment by travisbrown** [comment]
Sorry, accidentally hit the milestone button. :smile:

**Pull request merged**
