### PR TITLE
Doc fixups

### PR DESCRIPTION
**Pull request by longcao**
This PR attempts to address parts of https://github.com/typelevel/cats/issues/403.

The good bits:

- Fix up local-server jekyll script
- Freshen up links to scala-exercises and herding cats
- Move `tut`-checked docs to `typeclasses` and `datatypes` subfolders
  - Removes 'tut' from URL paths
  - This will change doc urls to be the following path scheme: `http://$BASEURL/cats/typeclasses/*.html` and `http://$BASEURL/cats/datatypes/*.html`
- Group typeclasses as suggested by https://github.com/typelevel/cats/issues/403#issuecomment-146160208 and similar to the [scala-exercises](https://www.scala-exercises.org) list.
- Move `Id` link + docs to data types

This is how it looks on my local machine:
screenshot 2016-09-01 15 17 45

**Note:** I don't have really good/original names for the groupings. Taking suggestions for names (and for the ordering) since Group 1, 2, 3, and Misc are by and large just placeholders.

This is mostly cosmetic but any links to the old docs URLs will break, e.g. http://typelevel.org/cats/tut/kleisli.html. Let me know if this PR is ok.

### CODE REVIEW

**Comment by non** [comment]
This looks like a big improvement! Thanks!

I'm fine merging this now and working on groupings as a follow-up. Alternately, I can take some time and try to come up with good groupings to suggest for this PR.

**Comment by longcao** [comment]
@non makes sense. The groupings seem fairly independent so maybe thinking of them as 'tracks' might help as well. Let me know what you might be thinking of.

**Comment by ceedubs** [comment]
Thanks, @longcao! I like these changes.

One thing I'm not entirely sure about is whether we want to try to group like this. No matter how we break down the groups you are going to have some cross-cutting concerns since `Traverse` extends both `Foldable` and `Functor`. Maybe it's fine to ignore this fact when grouping, as I think `Foldable` is the more natural segue into `Traverse`. But I find myself wondering if it would be better to just have a single track of type classes increasing in complexity (I think `Semigroup` is a natural first one). I'm not sure, I could really be convinced either way on this.

**Comment by longcao** [comment]
@ceedubs yeah - and I'm easily convinced of either! I do also agree that `Semigroup` + `Monoid` is an easy starting point for anyone with zero knowledge.

**Comment by longcao** [comment]
I just saw https://github.com/typelevel/cats/pull/1369, which totally looks awesome and seems to supercede/conflict the work done here, so I'm closing this PR in favor of tacking on some follow-on commits with https://github.com/typelevel/cats/pull/1369 after it gets merged.

**Pull request closed without merging**
