### PR TITLE
Add Env/Coreader/Product comonad

### PR DESCRIPTION
**Pull request by andyscott**
Adds Env/Coreader/Product comonad.

This is missing tests and documentation. I'd like to get a feel for whether or not this is a welcomed addition to cats before I go ahead and implement the rest. I filed an issue as well, see #1729. Thanks!

### CODE REVIEW

**Comment by kailuowang** [comment]
@andyscott what are your thoughts on this PR given the feedbacks in #1729?

**Comment by andyscott** [comment]
I have also been using `EnvT` as a pattern functor for `Cofree` in some private code. I'm happy to finish the PR if we'd like to get this merged into cats.

In general, Cats has missing odds and ends-- but I'd hate to see the core become bloated by adding them all. I think we ultimately need these odds and ends, and ideally we want them in maintained in a modular fashion so other libraries can use them.

With that in mind, I'd argue there should ultimately be auxiliary modules for cats (either as a submodule in this repo, or in a separate repo).

But again, I'm happy to finish this PR for the core module :).

**Comment by kailuowang** [comment]
> In general, Cats has missing odds and ends-- but I'd hate to see the core become bloated by adding them all. I think we ultimately need these odds and ends, and ideally we want them in maintained in a modular fashion so other libraries can use them.

I have the same thoughts. Also locking down `cats-core` bincomp probably means that practically new additions like this would have to be added as separate modules anyway. 
We could start a new module and label it as "experimental" which means no backward compat guarantee until we remove the label. 
The question in this particular matter is that does this EnvT justify a new module? If so how shall we name the module?

**Comment by andyscott** [comment]
A few notes on potentially adding a new module:

- For the name of a new module, I would prefer to avoid the "experimental" moniker anywhere in the path. For me it has a slightly negative association, especially with regards to using it in production software. I think something along the lines of `cats-addendum` or `cats-auxiliary` would be nice. Or `cats-adjunct` if you want a fun name.

- Items added to the new module could eventually be moved to the core cats module if they become cornerstone.

- Would this new module live in this repo? Or should it be a new repo? (ideally under TL).

- `EnvT` on its own right doesn't justify a whole new module. But I think we could easily assemble some odds and ends in order to justify the new module.

- How would we package items added to the new module? Would `cats.data.aux.EnvT`, for example, be a safe path?

If we go this route, I am happy to jump start it.

**Comment by kailuowang** [comment]
We might want to open a new issue to bikeshed about this new module.

**Pull request closed without merging**
