### PR TITLE
add a favicon for sbt-microsite

### PR DESCRIPTION
**Pull request by larsrh**
Turns out there is a hardcoded path to a favicon in sbt-microsite, which is currently a broken link.

With this link, users browsing the Cats page should hopefully see a :cat: in the tab bar.

### CODE REVIEW

**Comment by kailuowang** [comment]
👍

**Comment by larsrh** [comment]
Fun fact: this is my first pull request to Cats. *late to the party*

**Comment by kailuowang** [comment]
Now you are on the contributor list :)

**Comment by larsrh** [comment]
Success!

screenshot_20170131_090320

**Pull request merged**
