### PR TITLE
Rename std package to instances

### PR DESCRIPTION
**Pull request by ceedubs**
For #1135.

So far I haven't renamed the `std` within `kernel`. I'm happy to make
those changes as well, but I wanted to check with @non and @johnynek.

I also didn't rename all of the `catsStdX` instances. Those names seemed
fine to me, and some of them have names like `catsStdInstancesForList`,
which doesn't translate well if you switch `Std` to `Instances`.

### CODE REVIEW

**Comment by kailuowang** [comment]
:+1:

**Comment by johnynek** [comment]
👍 please go ahead and change kernel. We should stabilize now before it is used too much.

**Comment by ceedubs** [comment]
@johnynek @kailuowang I've updated the PR to include the change for kernel as well.

**Comment by kailuowang** [comment]
:+1:

**Comment by johnynek** [comment]
👍

**Comment by non** [comment]
👍 (once the conflicts are resolved)

**Comment by ceedubs** [comment]
Interesting - I didn't have to resolve any merge conflicts when I merged in master.

**Pull request merged**
