### PR TITLE
Add extension syntax for instantiating EitherT/OptionT from F[Either]/F[Option]

### PR DESCRIPTION
**Pull request by bplommer**

### CODE REVIEW

**Comment by jhnsmth** [comment]
Are there any chances to get this merged ? I'm happy to help with updating this PR and resolving conflicts

**Comment by rossabaker** [comment]
Sorry that this one escaped notice.

What is the advantage to this over the apply methods that already exist?  Does it improve type inference in some way?

**Comment by bplommer** [comment]
> What is the advantage to this over the apply methods that already exist? Does it improve type inference in some way?

No, it's purely a convenience method to support method chaining.

**Comment by bplommer** [comment]
I didn't do a great job of selling this back in... blimey, the end of the before times.

Finding myself once again working in some `EitherT`-heavy code bases though, I still think it's a good idea. Any thoughts?

**Comment by bplommer** [comment]
I've messed something up with updating the bincompat mixins - will fix if the idea is approved.

**Comment by rossabaker** [comment]
I wondered whether mouse had something like this, and as of 10 days ago, [it does](https://github.com/typelevel/mouse/pull/260).  I think that's the right place for it.

**Comment by armanbilge** [comment]
Yep, this seems to have found a good home in mouse.

**Pull request closed without merging**
