### PR TITLE
Backport tuple order fix for 0.6.x

### PR DESCRIPTION
**Pull request by ceedubs**
This PR (which is against the `series/0.6.x` branch that I just created) does a couple of things:
- Backport the tuple order fix from #1062 
- Add a binary compatibility check to all published modules (since we will want to maintain binary compatibility within the 0.6.x series)

I will largely unavailable for a little over a week, but I thought that if I got this branch set up someone else (@non?) might be able to get a 0.6.1 published with the fix for this pretty nasty bug.

cc @mpilquist and @travisbrown who have both expressed interest in getting this backported for a 0.6.1 release.

### CODE REVIEW

**Comment by travisbrown** [comment]
Thanks, @ceedubs! This looks good to me.

**Comment by non** [comment]
👍

**Comment by kailuowang** [comment]
👍

**Comment by kailuowang** [comment]
I checked out the code on my machine, the `mimaReportBinaryIssues`, when ran under root project, crashes with exit code 255 without error output. but if I run it under project coreJVM you get the following error. So somehow the released 0.6.0 binary is somewhere before this commit:
https://github.com/typelevel/cats/commit/a77beec0d58c267a4d8e32bcc9c856871d7c1184
(which is in the 0.6.0 tag), or mima pulled down a different binary? 


> [info] core: found 8 potential binary incompatibilities while checking against org.typelevel:cats-core_2.11:0.6.0 
> [error]  * the type hierarchy of object cats.implicits is different in current version. Missing types {cats.syntax.ApplicativeErrorSyntax1}
> [error]    filter with: ProblemFilters.exclude[MissingTypesProblem]("cats.implicits$")
> [error]  * the type hierarchy of trait cats.syntax.ApplicativeErrorSyntax is different in current version. Missing types {cats.syntax.ApplicativeErrorSyntax1}
> [error]    filter with: ProblemFilters.exclude[MissingTypesProblem]("cats.syntax.ApplicativeErrorSyntax")
> [error]  * trait cats.syntax.ApplicativeErrorSyntax1 does not have a correspondent in current version
> [error]    filter with: ProblemFilters.exclude[MissingClassProblem]("cats.syntax.ApplicativeErrorSyntax1")
> [error]  * the type hierarchy of interface cats.syntax.AllSyntax is different in current version. Missing types {cats.syntax.ApplicativeErrorSyntax1}
> [error]    filter with: ProblemFilters.exclude[MissingTypesProblem]("cats.syntax.AllSyntax")
> [error]  * method combine(cats.data.XorT,cats.Apply,cats.kernel.Semigroup,cats.kernel.Semigroup)cats.data.XorT in class cats.data.XorT does not have a correspondent in current version
> [error]    filter with: ProblemFilters.exclude[DirectMissingMethodProblem]("cats.data.XorT.combine")
> [error]  * method xorMonoid(cats.kernel.Semigroup,cats.kernel.Monoid)cats.kernel.Monoid in class cats.data.XorInstances does not have a correspondent in current version
> [error]    filter with: ProblemFilters.exclude[DirectMissingMethodProblem]("cats.data.XorInstances.xorMonoid")
> [error]  * method combine(cats.data.Xor,cats.kernel.Semigroup,cats.kernel.Semigroup)cats.data.Xor in class cats.data.Xor does not have a correspondent in current version
> [error]    filter with: ProblemFilters.exclude[DirectMissingMethodProblem]("cats.data.Xor.combine")
> [error]  * method xorSemigroup(cats.kernel.Semigroup,cats.kernel.Semigroup)cats.kernel.Semigroup in class cats.data.XorInstances1 does not have a correspondent in current version
> [error]    filter with: ProblemFilters.exclude[DirectMissingMethodProblem]("cats.data.XorInstances1.xorSemigroup")
> [trace] Stack trace suppressed: run last coreJVM/*:mimaReportBinaryIssues for the full output.
> [error] (coreJVM/*:mimaReportBinaryIssues) core: Binary compatibility check failed!
> [error] Total time: 1 s, completed Jul 6, 2016 5:36:08 PM
>

**Comment by ceedubs** [comment]
@kailuowang thanks for investigating this. I was on vacation, but I'm back now and will try to follow up on this.

**Comment by ceedubs** [comment]
Okay the build issue seems to be fixed with https://github.com/typelevel/cats/pull/1173/commits/e8b7ce4bd5ae0c01899046d906576f9717206676

@kailuowang I couldn't reproduce the compatibility issue that you showed. Is it possible that you have a locally-published version of cats 0.6 that mima is picking up?

I think this is probably ready to merge, but I think I'll need help from @non or someone else who can publish to get this out there. At some point I should probably get set up to be able to publish to Sonatype for cats.

**Comment by kailuowang** [comment]
@ceedubs ah that might be the case, I do have a local cats 0.6 😊 
Sorry about the confusion. 
This LGTM 👍

**Pull request merged**
