### PR TITLE
Add bisequence and bimap examples

### PR DESCRIPTION
**Pull request by ceedubs**
This was originally part of #1194, but since it's looking uncertain
whether or not that will go forward, I'm submitting it separately.

### CODE REVIEW

**Comment by adelbertc** [comment]
:+1: on Travis green

**Comment by fthomas** [comment]
@ceedubs All result variables have the name `res0` which could be confusing. Could you rename them to `res0`, `res1`, `res2`, etc. so that the example looks like a real REPL session?

**Comment by ceedubs** [comment]
Good catch @fthomas. Fixed.

**Comment by fthomas** [comment]
:+1:

**Pull request merged**
