### PR TITLE
Bump scalatest version to 3.0.3

### PR DESCRIPTION
**Pull request by shokohara**
I updated scalatest version to 3.0.3.

### CODE REVIEW

**Comment by shokohara** [comment]
@kailuowang 🙏  Thank you for helping. I'll try to fix it.

**Comment by shokohara** [comment]
I tried to rebuild on travis of my account.
The result is looks all green and cause of failure was just network error, so could you press `Restart build` on Travis and merge, please?

The result: https://travis-ci.org/shokohara/cats/builds/261841210

**Comment by tpolecat** [comment]
Can you bump it to 3.0.4? Just came out.

**Comment by shokohara** [comment]
@tpolecat Sure.

**Pull request merged**
