### PR TITLE
Removed deprecation of >> and changed its param to be a by-name

### PR DESCRIPTION
**Pull request by mpilquist**
In FS2, we rely heavily on recursive functions that return values of type `Pull[F,O,R]`. These functions typically take a form similar to:

```scala
def foo: Pull[F,O,R] =
  if (guard) Pull.done else doSomeWork *> foo
```

Recently, @pchlupacek noticed that FS2 defines `*>` with a by-name param whereas cats defines `*>` with a strict param. Such recursive programs are broken if we use a strict param. Hence, we are going to change the FS2 definition of `*>` to be strict and reintroduce `>>` with a by-name param and then use `>>` in all recursive pulls.

Ideally, cats would have the same definition for `>>`, so in this PR I removed the deprecation of `>>` and defined it with a by-name param, making it a true alias for `flatMap(_ => fb)`. Note that we already have `followedByEval` and `forEffectEval`, though the syntax overhead of using those is way too high IMO.

### CODE REVIEW

**Comment by LukaJCB** [comment]
I'm generally +1 on this, but should we maybe move it to `Apply`?

**Comment by mpilquist** [comment]
I thought about that but settled on leaving `>>` on `FlatMap` since the guarantee is that `fb` won't be computed until `fa` produces an `A` (precisely what `flatMap` describes).

**Comment by LukaJCB** [comment]
I see, yeah I think that makes sense! :)

**Comment by LukaJCB** [comment]
I think you'll need to add a mima exception

**Comment by mpilquist** [comment]
Yeah, just pushed a mima fix.

**Pull request merged**
