### PR TITLE
cats logo as svg and new "cats friendly" badge

### PR DESCRIPTION
**Pull request by thoefer**
* add original, pixelated cats logo as svg image (#2486)

* add new "cats friendly" badge as svg image (#1807)

* add exported .png images of both also

### CODE REVIEW

**Comment by thoefer** [comment]
TravisCI gave me a "No output has been received in the last 10m0s" on Scala. 2.13... not sure why that happens. I triggered a rebuild again.

**Comment by kailuowang** [comment]
Thank so much! Once this is merge, we could update the README.md to provide it on the homepage.

**Comment by rossabaker** [comment]
What's the recommended way for projects to embed these?  Copy them into our repos?  Solemnly swear that we'll never change the URL?

**Comment by kailuowang** [comment]
I think copy them to their own repos might be easier. do we need to specify the license of this and the Cats logo? or MIT is going to cover this?

**Comment by thoefer** [comment]
Embedding them with a link to our repo has the advantage that we can change it later and other have an always up-to-date version without any work on their side.

**Comment by kailuowang** [comment]
Let's merge this and add links to the README

**Pull request merged**
