### PR TITLE
scaladex badge

### PR DESCRIPTION
**Pull request by MasseGuillaume**
in action: https://github.com/MasseGuillaume/cats/tree/scaladex-badge#cats

### CODE REVIEW

**Comment by non** [comment]
Looks good to me. 👍 Thanks!

**Comment by fthomas** [comment]
Nice! Could you change the style from `flat-square` to just `flat`. Most of the other badges use that style.

**Comment by MasseGuillaume** [comment]
style is now flat

**Comment by fthomas** [comment]
Many thanks!

**Pull request merged**
