### PR TITLE
Add Hash and Order Instances for NonEmptyVector

### PR DESCRIPTION
**Pull request by isomarcte**

### CODE REVIEW

**Review by rossabaker — COMMENTED** [review]
While we're in this part of the hierarchy, does `PartialOrder` make sense?

**Comment by rossabaker** [comment]
Reran the nuisance native failure.

**Comment by isomarcte** [comment]
> While we're in this part of the hierarchy, does `PartialOrder` make sense?

@rossabaker added

**Comment by rossabaker** [comment]
I think this works, but while we wait for CI: in `Chain`, `PartialOrder` is higher priority than `Hash`.  Here, that relative order is flipped.  I don't think it matters between this pair, but we're leaving the comfortable precedent of `Chain`.

**Comment by isomarcte** [comment]
@rossabaker updated to match the Chain priority.

**Review by rossabaker — APPROVED** [review]

**Review by satorg — APPROVED** [review]
Thanks!

**Pull request merged**
