### PR TITLE
Update Scala 2.12 to 2.12.9

### PR DESCRIPTION
**Pull request by jhnsmth**

### CODE REVIEW

**Comment by jhnsmth** [comment]
CI failure seems unrelated...

**Comment by kailuowang** [comment]
hi, @jhnsmth thanks for the PR. 
BTW, you didn't have to close and reopen the PR to trigger the CI build. Maintainers can rerun the single failed job.

**Comment by takayahilton** [comment]
https://github.com/scala/bug/issues/11665
we should wait until the release of 2.12.10 ?

**Comment by djspiewak** [comment]
@takayahilton Not sure that bug is relevant to cats, given that we don't really use string interpolation very much. It's possible though.

**Pull request merged**
