### PR TITLE
Using regular syntax in the FreeApplicative tutorial (#1471)

### PR DESCRIPTION
**Pull request by denisftw**
As suggested in #1471, this PR adjusts examples in the FreeApplicative tutorial to use regular syntax instead of kind projector's lambdas.

### CODE REVIEW

**Comment by peterneyens** [comment]
Thanks @denisftw :+1:

**Comment by kailuowang** [comment]
I think it makes sense to use the regular syntax in the example. But [polymorphic lambdas](https://github.com/non/kind-projector/#polymorphic-lambda-values) was very handy in such situations. And if I remember correctly, such application in Free was one of the incentives of introducing polymorphic lambda in kind projector. We also use it in cats code. It might be worthwhile to mention polymorphic lambda here and use one of the `FunctionK` instance as an example? Something like, 
```
or with  [polymorphic lambdas](https://github.com/non/kind-projector/#polymorphic-lambda-values) provided by kind-projector, you can write compiler as 
 val compiler = λ[FunctionK[ValidationOp, FromString]] { fa => 
    ....
```
 @denisftw @peterneyens what do you guys think?

**Comment by peterneyens** [comment]
It is indeed a good idea to mention the polymorphic lambda syntax and include such an example.

We could probably also add something about the polymorphic lambda syntax to the [section about kind projector](https://github.com/typelevel/cats/blob/master/docs/src/main/tut/faq.md#what-do-types-like--and-%CE%BB-mean) in the FAQ.

**Comment by non** [comment]
Sounds good to me. 👍

**Comment by johnynek** [comment]
This one fell through the cracks.

I'm +1 on what has been said:

1. for beginners, use the verbose syntax.
2. also explain that it could have been written using the compiler plugin with the lambda syntax.

**Comment by ceedubs** [comment]
Thanks @denisftw! I really like this change. I'm sorry that it fell between the cracks.

I'm 👍 on merging this, and there are now `FunctionK` docs that describe using the polymorphic lambda syntax, so I don't think that we need to duplicate it in the `FreeApplicative` docs.

Unfortunately, there is a merge conflict. Would you want to resolve that? If not, I can take your work and turn it into a new PR.

**Comment by denisftw** [comment]
Sure, I'll take a look tomorrow.

**Comment by ceedubs** [comment]
Thanks @denisftw!

**Pull request merged**
