### PR TITLE
Backport #2772 add `foldRightDefer` to Foldable

### PR DESCRIPTION
**Pull request by gagandeepkalra**
addresses #3143

### CODE REVIEW

**Comment by gagandeepkalra** [comment]
> java.lang.RuntimeException: Cats laws: Binary compatibility check failed!

I see other laws added without care for BC, did we add this constraint recently?

It's gonna be tricky to follow through with this.

**Comment by travisbrown** [comment]
We've always guaranteed (and checked) bincompat within 2.x for laws on mainline, and I think we should on the 2.11 branch as well (note that this kind of addition only breaks bincompat on 2.11).

My vote would be just not to include the consistency law on this branch, possibly adding a comment to the method along the lines of "Implementers are responsible for ensuring the maintain consistency with `foldRight`; this is not checked by laws on Scala 2.11".

**Comment by gagandeepkalra** [comment]
@travisbrown Think I'm a little confused, I see this added in May yet no BC problem.

Screenshot 2020-03-06 at 10 06 33 PM

yes, adding `foldRightDefer` would only break BC on 2.11, but how was the above law added given it is part of 2.11.

**Comment by travisbrown** [comment]
@gagandeepkalra See @kailuowang's comment on #2817:

> BTW, strictly speaking this is breaking change for `UnorderedFoldableLaws` but it's unlikely to affect anyone and we are breaking BC in cats-laws in our next release.

And mine above:

> We've always guaranteed (and checked) bincompat within 2.x for laws on mainline

That addition was first included in 2.0.0, so while it was a breaking change since 1.x on Scala 2.11, we'd decided that that was okay for cats-laws (we only guaranteed 100% bincompat across 1.x and 2.x for cats-core, etc.).

**Comment by gagandeepkalra** [comment]
I see, thank you. Apologies for not checking the PR first 😔

**Comment by travisbrown** [comment]
No worries, glad that helped!

**Pull request merged**
