### PR TITLE
Add Future Order tests

### PR DESCRIPTION
**Pull request by adelbertc**

### CODE REVIEW

**Comment by non** [comment]
:+1:

**Comment by ceedubs** [comment]
Thanks @adelbertc. I'm not so sure about this because of #589. Have you taken a look at that issue?

**Comment by adelbertc** [comment]
@ceedubs Just read through it again - the problem is the unlawfulness assumes side effects right? e.g. throwing exceptions, at which point we can't say anything about anything. In the absence of such things it appears to work

**Comment by ceedubs** [comment]
@adelbertc I don't think I quite see it that way. A failed `Future` is a perfectly valid case of a `Future` (similar to an `Xor.Left`), and it can be created without throwing exceptions. It's the `Order[Future]` instance that throws for a perfectly valid `Future` and therefore is the problematic piece (beyond blocking) in my opinion.

**Comment by adelbertc** [comment]
Ah fair.. in which case these test are bogus I think.

**Pull request closed without merging**
