### PR TITLE
Add law-checking for asMeetPartialOrder and asJoinPartialOrder

### PR DESCRIPTION
**Pull request by ceedubs**

### CODE REVIEW

**Comment by ceedubs** [comment]
hmm I don't understand why this didn't affect code coverage. I'll have to
investigate.

**Comment by ceedubs** [comment]
I think that the `build`/`validate` aliases in the `build.sbt` aren't quite right. I'm testing some changes locally and should be adding a commit to this PR shortly.

**Comment by non** [comment]
Sounds good. I'm 👍 on this PR either way.

**Comment by ceedubs** [comment]
Okay, I'm not quite sure what codecov is complaining about now, but it looks like the build changes resulted in +6% coverage being reported.

**Comment by adelbertc** [comment]
:+1: woot woot!

**Pull request merged**
