### PR TITLE
Add `MonadError.rethrow`

### PR DESCRIPTION
**Pull request by SystemFw**
This PR seeks to add `rethrow` to `MonadError`, i.e. the inverse of  `attempt`. 
The law for it is currently failing on `IorT`.

### CODE REVIEW

**Comment by kailuowang** [comment]
still have scala style errors
> [error] /home/travis/build/typelevel/cats/core/src/main/scala/cats/MonadError.scala:47:4: Whitespace at end of line
[error] /home/travis/build/typelevel/cats/core/src/main/scala/cats/MonadError.scala:52:4: Whitespace at end of line
[error] /home/travis/build/typelevel/cats/core/src/main/scala/cats/MonadError.scala:56:4: Whitespace at end of line
[error] /home/travis/build/typelevel/cats/core/src/main/scala/cats/MonadError.scala:61:5: Whitespace at end of line

and also need to add mima exceptions to [here](https://github.com/typelevel/cats/blob/master/build.sbt#L198)

**Comment by SystemFw** [comment]
@kailuowang you are too kind :)

**Comment by johnynek** [comment]
:+1:

**Comment by kailuowang** [comment]
We already have 2 sign-offs, but since I made a couple lines of changes here. Maybe @LukaJCB can give it another look?

**Comment by mpilquist** [comment]
Is it weird to call this `rethrow` when `E` could be any type (i.e. not a `Throwable`)?

**Comment by SystemFw** [comment]
It is a bit weird, and we had a brief discussion on gitter cause I was not sure about the original name.
I started with `absolve`, then `materialize/unmaterialize` were floating around, in the end I've settled with `rethrow`. `reraise` is more consistent I guess, but it's fairly ugly as well

**Comment by mpilquist** [comment]
:) I have no objections

**Comment by kailuowang** [comment]
Hmm I do like `reraise` better, not a strong preference though

**Comment by SystemFw** [comment]
I don't have  a strong preference either tbh

**Comment by kailuowang** [comment]
do you want to change to `reraise`? or I can make another PR against your branch?

**Comment by SystemFw** [comment]
It's past two so I won't be able to do anything until tomorrow
Go ahead if you have time though :)

**Comment by kailuowang** [comment]
never mind about the rename, I noticed that the word "rethrow" is already used numerous time in `MonadError`'s doc.

**Pull request merged**
