### PR TITLE
Add a missing T

### PR DESCRIPTION
**Pull request by andyscott**
Adds a missing T.

### CODE REVIEW

**Comment by LukaJCB** [comment]
Wait, this is potentially binary breaking, is it not? 🤔

**Comment by LukaJCB** [comment]
Yeah seems, like it. I'm gonna file this one for 2.0 :)

**Comment by mcanlas** [comment]
Just driving by. @LukaJCB Is there a resource/document that outlines which changes are binary breaking and which are not? And isn't there a tool that helps with this also?

**Comment by kailuowang** [comment]
Yeah it's BC breaking.

**Comment by andyscott** [comment]
Indeed!

**Comment by LukaJCB** [comment]
@mcanlas Check out mima, it's the tool we use and it also describes what's binary breaking :)

**Comment by kailuowang** [comment]
@mcanlas rule of thumbs is that 
1. you can't change any existing public members. 
2. you can't add a new method to a trait even if you give it a default implementation. 

@andyscott if we really care about this name we could simply change the existing to explicit and add a new implicit one with the correct name, although I am not sure if that's better than a miss-spell.

@LukaJCB this would be BC breaking on scala 2.12 as well. For 2.0 we still want 2.12 BC right?

**Pull request closed without merging**
