### PR TITLE
Add leftTraverse and leftSequence to Bitraverse typeclass

### PR DESCRIPTION
**Pull request by ikempf**
Bitraverse should offer "left" traversing functionality.
Right-traversal is already offered through Traverse typeclass, bi-traversal and left-traversal should both be offered by Bitraverse. This keeps it consistent with Bifunctor (which offers leftMap).

This resolves issue #2474

### CODE REVIEW

**Comment by kailuowang** [comment]
Unfortunately we can't add methods to traits without breaking binary compatibility on Scala 2.11.
You can add this to a new syntax extension trait like in #2588.

**Comment by ikempf** [comment]
I removed methods from existing traits (Bitraverse and BitraverseSyntax) and moved everything into a new trait BitraverseSyntaxBinCompat0 that is extended by AllSyntaxBinCompat3 and bitraverse.

**Comment by LukaJCB** [comment]
Seems like this is a duplicate of https://github.com/typelevel/cats/pull/2606

**Comment by ikempf** [comment]
@LukaJCB You are right it is a duplicate

**Pull request closed without merging**
