### PR TITLE
Invariant For Applicative Error

### PR DESCRIPTION
**Pull request by ChristopherDavenport**
Baseline is just an implementation of Invariant for ApplicativeErrors error type. Not sure if this is wanted so wanted to open discussion before I built out the full tests.

### CODE REVIEW

**Comment by ceedubs** [comment]
I can't say that I've encountered a need for this personally, but it looks reasonable to me, and admittedly I don't use many of the MTL classes much (probably to a fault).

This does make me mentally go down a rabbit hole of how much more Cats could be doing with instances based on isomorphisms, but I probably shouldn't open up that can of worms here :)

**Comment by kailuowang** [comment]
@LukaJCB it's not ready for review yet, just would like to hear your opinion on this one.

**Comment by LukaJCB** [comment]
I haven't encountered the need for this yet either personally, but we already have typeclass instances for a bunch of other type classes, so I think this is a good addition :)

**Comment by larsrh** [comment]
Closing this for lack of activity.

**Pull request closed without merging**
