### PR TITLE
Fix broken documentation links

### PR DESCRIPTION
**Pull request by liff**
`/tut/` leads to a 404.

### CODE REVIEW

**Comment by peterneyens** [comment]
HI @liff, thanks for spotting this.

`grep "tut/" -r --exclude-dir "*target*" cats/` gives us a lot of similar errors, but I will open another issue for this.

**Comment by liff** [comment]
I can add fixes for the other broken links in this PR if that's OK?

**Comment by peterneyens** [comment]
Of course, that would be great.

**Comment by liff** [comment]
Here you go.

There's one more [broken link to Arrow.scala](https://github.com/typelevel/cats/blame/master/docs/src/main/tut/faq.md#L198) in the FAQ but I'm not sure where it should point to exactly.

**Comment by peterneyens** [comment]
I think we lost `{{ site.sources }}` with the new site (It was in this [removed file](https://github.com/typelevel/cats/pull/1369/files#diff-5834e29d7dd3bb9c2cbd367847a9d4ecL10)).

We can probably fix that in another PR.

**Comment by non** [comment]
👍 Thanks for fixing this!

**Comment by peterneyens** [comment]
:+1:

**Pull request merged**
