### PR TITLE
Stack-safe foldM

### PR DESCRIPTION
**Pull request by TomasMikula**
This is based off #356, but adds back stack-safety.

### CODE REVIEW

**Comment by eed3si9n** [comment]
I'm passing the torch to you.

**Comment by eed3si9n** [comment]
> No output has been received in the last 10 minutes, this potentially indicates a stalled build or something wrong with the build itself.

Could someone restart the Travis job for 2.10.x, please?

**Comment by ceedubs** [comment]
:+1: thank you @TomasMikula and @eed3si9n!

**Comment by stew** [comment]
:+1:

**Pull request merged**
