### PR TITLE
Add Bitraverse, fixes #800

### LINKED ISSUE #800: Bitraverse type class

### PR DESCRIPTION
**Pull request by adelbertc**
Review by @travisbrown

### CODE REVIEW

**Comment by adelbertc** [comment]
Realized last night I sorta need this for my talk next week, please review soon :D

**Comment by travisbrown** [comment]
:+1:, looks great to me, but where's my `bitraverseU`? :smile:

**Comment by adelbertc** [comment]
@travisbrown I tried! I ran into a problem when I tried something like:

```scala
def bitraverseU[A, B, GC, GD](fab: F[A, B])(f: A => GC, g: B => GD)(implicit ULeft: Unapply[Applicative, GC], URight: Unapply[Applicative, GD]) = ???
```

and I needed to make sure `ULeft.M` was the same as `URight.M`. Maybe I'm encoding it wrong.. halp :-)

**Comment by travisbrown** [comment]
@adelbertc That was kind of a joke—I've got [a huge blog post](https://meta.plasm.us/posts/2015/07/11/roll-your-own-scala/) on exactly that problem. My fix is in Scalaz, but I'm not sure it's worth it.

**Comment by adelbertc** [comment]
@travisbrown ah :-) on one hand I'm glad to see I wasn't crazy, on the other hand I'm also kind of sad

**Comment by non** [comment]
Looks good to me. :+1:

**Pull request merged**
