### PR TITLE
Add FP for Mortals entry to Microsite

### PR DESCRIPTION
**Pull request by emilypi**
Hi Everyone, 

As you know, Sam has finally finished his book, and a fair bit of it deals with Cats, as well as Scalaz. As the most modern resource on the subject of FP in Scala (chronologically), I feel it has a place here, considering it _is_ free and very well-written. Thanks.

### CODE REVIEW

**Comment by emilypi** [comment]
@LukaJCB can i get a hallelujah?

**Comment by stew** [comment]
Sam has been openly hostile the typelevel project, to the point of inventing and spreading lies about it and its members. 

I also don't think that  the book has an accurate description of cats.

**Comment by fommil** [comment]
I actually didn't feel cats, or typelevel, were relevant enough to mention.

**Comment by emilypi** [comment]
@stew which part wasn't accurate? The parent part? I can change that.

**Pull request closed without merging**
