### PR TITLE
Onward to scala 2.11.8.

### PR DESCRIPTION
**Pull request by paulp**
Unused import detection has improved, leading to a number
of deletions.

### CODE REVIEW

**Comment by paulp** [comment]
Oops, I accidentally snuck a couple new plugins in as well. That's actually what got me started on the whole thing, but I completely forgot until I skimmed the diff.

**Comment by mpilquist** [comment]
:+1:

**Comment by paulp** [comment]
So, let me know and I can carve off one or both of them. Coursier should be a slam dunk, the other one is a little more obscure - I just ran across it and found it handy.

screen shot 2016-03-18 at 7 04 28 am

**Comment by paulp** [comment]
Great! In my initial push the build failed because `op` was not found. After restoring it, the build fails because `op` is unused. It is perhaps unused during normal compilation but used during documentation generation. I don't know how to deal with this.
```
[info] Compiling 119 Scala sources to /home/travis/build/typelevel/cats/core/.jvm/target/scala-2.11/classes...
[error] /home/travis/build/typelevel/cats/core/src/main/scala/cats/SemigroupK.scala:3: Unused import
[error] import simulacrum.{op, typeclass}
[error]                    ^
[error] one error found
[error] (coreJVM/compile:compileIncremental) Compilation failed
```

**Comment by edmundnoble** [comment]
`op` is a macro annotation. Perhaps it's being expanded and removed, which is causing it to appear unused. I suggest fully qualifying the use of `op` for now and removing the import, seeing as it's the only use of `op` in the cats codebase. It looks like it will validate with that change.

**Comment by paulp** [comment]
Hah, I can't believe I didn't think of doing that.

**Comment by adelbertc** [comment]
:+1: on Travis green

**Comment by paulp** [comment]
It all seems fine, but the builds hang up:
```
No output has been received in the last 10 minutes, this potentially
indicates a stalled build or something wrong with the build itself.
The build has been terminated
```
On my last push I removed those two plugins in case one was causing this, but it has happened again since. Has this happened before? My first guess would be memory exhaustion though I don't know why this commit would cross any threshold.

**Comment by DavidGregory084** [comment]
@paulp this seems to happen fairly frequently at the minute, see #810 and associated issues

**Comment by fthomas** [comment]
I've restarted the build.

**Comment by adelbertc** [comment]
And restart again......

**Comment by ceedubs** [comment]
Fantastic. Thanks @paulp!

**Pull request merged**
