### PR TITLE
add -P:scalajs:mapSourceURI option

### PR DESCRIPTION
**Pull request by xuwei-k**

### CODE REVIEW

**Comment by milessabin** [comment]
Does this change the release tag name?

**Comment by xuwei-k** [comment]
> Does this change the release tag name?

No, this is `sbt-release` plugin's default `TaskKey[String]` value.
 
https://github.com/sbt/sbt-release/blob/v1.0.3/src/main/scala/ReleasePlugin.scala#L194

**Comment by milessabin** [comment]
Is there any way of using the release plugin's default value without duplicating the definition here?

**Comment by xuwei-k** [comment]
`releaseTagName` is `Task` but `scalacOptions` is `Setting`, `Setting` can not depends on `Task`.

**Comment by milessabin** [comment]
Gotcha.

**Comment by milessabin** [comment]
:+1:

**Comment by non** [comment]
Thanks! :+1:

**Pull request merged**
