### PR TITLE
Fix scalafix testing instructions

### PR DESCRIPTION
**Pull request by kubukoz**

### CODE REVIEW

**Comment by ChristopherDavenport** [comment]
I've always used `sbt "; ...;..."` when running multiple commands. I'm surprised that either of the above work well.

**Comment by kubukoz** [comment]
Well, it doesn't work on Mac as it is in the repo. I'm still figuring out the correct way, though ;)

**Comment by kubukoz** [comment]
In fact, I don't see the project `coreFree` at all...

**Comment by kubukoz** [comment]
`sbt coreJVM/publishLocal freeJVM/publishLocal` should do the job if I'm not mistaken in thinking that `freeJVM` is the correct replacement for `coreFree`. I'll update the PR once it's confirmed.

cc @LukaJCB, by chance?

**Comment by kubukoz** [comment]
Ahh, we need `macrosJVM/publishLocal` and `kernelJVM/publishLocal` as well

**Comment by kubukoz** [comment]
With all these subprojects we need to publish, maybe there's a way to just publish all things JVM? :)

**Comment by kailuowang** [comment]
On Travis it runs 
```
sbt ;coreJVM/publishLocal;freeJVM/publishLocal
cd scalafix
sbt tests/test
cd ..
```

**Comment by kubukoz** [comment]
Sorry, I didn't see your comment before.

Well, running `sbt ;coreJVM/publishLocal;freeJVM/publishLocal` doesn't seem to work with either zsh or bash on Mac (iterm2 / terminal are both affected). It just opens the sbt shell...

It seems right that for `tests/test` we only need coreJVM and freeJVM, so this should be portable enough, and I suggest to change the readme to:
`sbt coreJVM/publishLocal freeJVM/publishLocal`

the other modules were needed for the whole `test` task (and most likely for correct depedency resolution in IDEA). We might want to mention that in the readme too...

**Comment by kailuowang** [comment]
thanks very much! since this is very straightforward documentation correction, I am going to merge with 1 sign-off

**Pull request merged**
