### PR TITLE
Rename Gosub to FlatMapped

### PR DESCRIPTION
**Pull request by adelbertc**

### CODE REVIEW

**Comment by non** [comment]
I like it! Thanks! 👍

**Comment by ceedubs** [comment]
@adelbertc thanks! I like it a lot. Sorry, but I just created a conflict by merging #1085. Could you update your PR please?

**Comment by ceedubs** [comment]
@adelbertc bump :)

**Comment by adelbertc** [comment]
Sorry! Will get to it this weekend!

**Comment by ceedubs** [comment]
👍 as soon as the build succeeds.

**Pull request merged**
