### PR TITLE
Make NonEmptyList covariant

### PR DESCRIPTION
**Pull request by edmundnoble**
In which `NonEmptyList` and `ValidationNel` are made covariant.

### CODE REVIEW

**Comment by johnynek** [comment]
I'm +1 on this. I don't really buy the variance anxiety.

That said, you can always do `.widen[T]` to use `Functor` to get it to the type you want, which should cast, which should basically be free.

I think the cats position on variance is something that deserves a doc. I actually enjoy variance, but that seems to not be a popular opinion. I know subtyping in general is not widely admired due to how it complicates type inference, but I don't know of the concrete problems we have with covariance on data types, and I'd like to see them.

**Comment by edmundnoble** [comment]
I believe attaching variance to data types and not typeclasses is the current cats position; the thing is, variance composes much more easily than functors. Once you get more than one level deep, `Functor[F].compose(Functor[G]).widen(t)` starts to get much worse than just `t`.

**Comment by ceedubs** [comment]
I'm pretty late to the show, but 👍 from me. I think that this makes it consistent with data types like `Validated`. It sounds like we have 👍 from @johnynek, but since variance is a touchy subject I'd maybe like to get an opinion from at least one other person. @typelevel/cats what do you think?

**Comment by ceedubs** [comment]
Also, if we merge this, I think that we should do the same for `NonEmptyVector`.

**Comment by johnynek** [comment]
@non what do you say? I'm still +1 on data types having variance.

**Comment by non** [comment]
I'm 👍 on this. I think a position of *variance on data types is fine, but not type classes* sounds like something that could work and would be consistent.

If there are concrete problems folks can point to with variance on data types then I'm open to revisiting this position.

**Comment by johnynek** [comment]
Note, I think we will need to merge master here since there may have been
some methods added to NonEmptyList since this was created.

**Comment by edmundnoble** [comment]
Rebased, with `NonEmptyVector` added to the party.

**Comment by johnynek** [comment]
👍

**Comment by kailuowang** [comment]
👍

**Comment by ceedubs** [comment]
👍 thanks, @edmundnoble!

**Pull request merged**
