### PR TITLE
Delete PR template

### PR DESCRIPTION
**Pull request by joroKr21**
Stop asking contributors to run `+prePR`.
That's a way too heavy operation for a laptop due to Scala native. It's better to open a PR and let CI check it.

> Thank you for contributing to Cats!

> This is a kind reminder to run `sbt +prePR` and commit the changed files, if any, before submitting.

No, thanks! I have to `kill -9` it if I try 😄

### CODE REVIEW

**Review by danicheg — APPROVED** [review]
Tend to agree with this removal. But according to the `cats` usage of Scala Native, a regular contributor could unlikely break it. Maybe we can create some handy alias for JVM only?

**Comment by joroKr21** [comment]
Perhaps. I couldn't find where it's defined so I'm not even sure what it does 🤔

**Review by armanbilge — APPROVED** [review]
I also agree, regardless of Scala Native `+prePR` is always hitting a nail with a hammer. Chances are you actually only need to format 1 or 2 files you happened to touch (I use right-click in VSCode metals to do this per-file, there's also a shortcut).

I think it would still be useful to have some guide for users here. Fortunately all projects are working the same so maybe we can add something to sbt-typelevel docs and link to it from all the Typelevel PR templates. e.g. if formatting fails in CI, run `scalafmt`, if Scala version x.y.z fails to compile run `++ x.y.z compile`, etc.

**Comment by armanbilge** [comment]
> I couldn't find where it's defined

https://github.com/typelevel/sbt-typelevel/blob/8b7e77e91bd34038605eb71e8d78fb8a558321d6/core/src/main/scala/org/typelevel/sbt/TypelevelPlugin.scala#L88-L101

**Comment by joroKr21** [comment]
That doesn't look like something which can run only on the JVM subprojects

**Comment by satorg** [comment]
Thank you!

**Pull request merged**
