### PR TITLE
add unzip to Functor

### PR DESCRIPTION
**Pull request by gagandeepkalra**
addresses https://github.com/typelevel/cats/issues/3023

### CODE REVIEW

**Comment by gagandeepkalra** [comment]
I need some help with this weird compiler situation

> [error] /home/travis/build/typelevel/cats/core/src/main/scala/cats/Functor.scala:56:21: not found: type A
[error]   def widen[A, B >: A](fa: F[A]): F[B] = fa.asInstanceOf[F[B]]
[error]                     ^
[error] /home/travis/build/typelevel/cats/core/src/main/scala/cats/Functor.scala:12:2: type arguments [C,B] do not conform to method widen's type parameter bounds [A,B >: A]
[error] @typeclass trait Functor[F[_]] extends Invariant[F] { self =>
[error]  ^
[error] two errors found

the current version won't compile, but if I just introduce a dummy parameter to unzip method, it works just fine. 

> def unzip[A, B](dummy: Int, fab: F[(A, B)]): (F[A], F[B]) = (map(fab)(_._1), map(fab)(_._2))

**Comment by oleg-py** [comment]
@gagandeepkalra looks like an issue with Simulacrum-generated extension method (from `@typeclass` annotation.

Annotating `unzip` with `@noop` helps too, and I think we have to do it anyway for bincompat reasons.

**Comment by gagandeepkalra** [comment]
> Annotating `unzip` with `@noop` helps too, and I think we have to do it anyway for bincompat reasons.

@oleg-py yes thank you, this fixes the compilation. I'm not so sure of the bincompat, I still get this error

> [error]  * method unzip(java.lang.Object)scala.Tuple2 in trait cats.Functor is present only in current version
[error]    filter with: ProblemFilters.exclude[[ReversedMissingMethodProblem]]("cats.Functor.unzip")
[error] java.lang.RuntimeException: Cats core: Binary compatibility check failed!

compiler suggested I add the above line to build.sbt, so I did, but I'm not sure this is the right way.

**Comment by gagandeepkalra** [comment]
@LukaJCB @kailuowang some eyes on this one please

**Comment by kailuowang** [comment]
Sorry I just realized the review comments I left earlier was in pending status and not actually posted. I suggested that it's odd that the mima bin compat check failed. I am curious, have you merged in the master?

**Comment by gagandeepkalra** [comment]
@kailuowang @oleg-py I updated the method signature.

`def unzip[A, A1, A2](fab: F[A])(implicit asPair: A => (A1, A2)): (F[A1], F[A2])` 

This fixed the Simulacrum error, we won't need `@noop` now.

**Comment by kailuowang** [comment]
> `def unzip[A, A1, A2](fab: F[A])(implicit asPair: A => (A1, A2)): (F[A1], F[A2])`

If I am not mistaken this relies on the implicit `$comply` in `Predef`. I am not familiar with this approach. But at the very least, it obscures the type signature.  Can you confirm again that the original version proposed in the issue breaks bincompat after you merged in master?

**Comment by gagandeepkalra** [comment]
> But at the very least, it obscures the type signature.

yes, agreed. I was trying to avoid using `@noop` here, since we no longer need it for bincompat reasons, which got fixed with the recent master as you suggested.

**Comment by travisbrown** [comment]
This looks fine to me.

**Comment by gagandeepkalra** [comment]
Thank you everyone

**Comment by yangzai** [comment]
(accidentally closed and reopened pr with an incomplete comment...)


@travisbrown As I was saying, the original attempt was a direct fix in the Functor trait that work with Simulacrum so it would be slightly beneficial if the intention is to move as much back to a single typeclass/trait when bincompat isn't an issue. However, having `FunctorTupleOps` per complex shape like `F[(A, B)]` seems like a defacto convention you would want to keep to. Let me know your thoughts.

On a side note regarding https://github.com/typelevel/cats/pull/3062#issuecomment-535743466 , having the type signature of `widen` changed to something like
```scala
  def widen[A, B: A <:< *](fa: F[A]): F[B] = fa.asInstanceOf[F[B]]
```
would fix(i.e. not require `@noop` for `unzip`) but that would break bincompat. Just an interesting note.

**Pull request merged**
