### PR TITLE
Cache List Monoid instance

### PR DESCRIPTION
**Pull request by TimWSpence**
See discussion on https://github.com/http4s/http4s/pull/6712

### CODE REVIEW

**Comment by armanbilge** [comment]
Er wait, is this a dupe of https://github.com/typelevel/cats/pull/4309 😛

**Comment by TimWSpence** [comment]
> Er wait, is this a dupe of #4309 😛

Yes 🤦

**Comment by armanbilge** [comment]
@TimWSpence not sure if @bplommer still has time to work on https://github.com/typelevel/cats/pull/4309, would you be interested to get it over the finish line? 🙏

**Comment by TimWSpence** [comment]
> @TimWSpence not sure if @bplommer still has time to work on #4309, would you be interested to get it over the finish line? 🙏

Yep sure, assuming Ben's happy!

**Pull request closed without merging**
