### PR TITLE
Update to Scala 2.12.0

### PR DESCRIPTION
**Pull request by travisbrown**
This PR includes @adamnfish's changes from #1450, together with the rest of the stuff we need for 2.12.0.

Note that because of [an issue](https://github.com/scoverage/sbt-scoverage/pull/201) in the 1.5.0 release of the sbt-scoverage plugin, it necessary to set the Scoverage compiler plugin version explicitly for the build:

```scala
coverageScalacPluginVersion := "1.3.0"
```

The issue should be fixed in the next sbt-scoverage release, and then it should be possible to remove that line.

### CODE REVIEW

**Comment by kailuowang** [comment]
Looks like there is a problem with the catalysts release. I am working on it now.

**Comment by travisbrown** [comment]
Thanks, @kailuowang! Looks like the missing artifact is there now, so hopefully this time it'll work.

**Comment by mandubian** [comment]
👍

**Comment by kailuowang** [comment]
:+1:

**Comment by alexandru** [comment]
👍

**Comment by adamnfish** [comment]
Thanks, @travisbrown!

**Comment by gslowikowski** [comment]
`coverageScalacPluginVersion := "1.3.0"` setting can be removed from `build.sbt`.

**Comment by travisbrown** [comment]
@gslowikowski How? Did you overwrite the 1.5.0 release on Maven Central? (Is that even possible?)

**Comment by travisbrown** [comment]
@gslowikowski In any case since this only affects the build and is the same behavior you'd get without the line, I'd say let's get this PR merged asap and remove the line in a follow-up PR.

**Comment by non** [comment]
👍

**Comment by gslowikowski** [comment]
@travisbrown sure, I just wanted to let you know, that I fixed the snapshot problem before syncing to Maven central

**Comment by travisbrown** [comment]
@gslowikowski This is getting off-topic for this PR (now that it's merged it probably doesn't matter), but did you figure out why the artifacts made it to Sonatype releases but hadn't been synced to MC after more than a day?

**Comment by gslowikowski** [comment]
I didn't ask. I was happy, that because of this delay I could ask Sonatype team to break this buggy release. I've had similar problem in the past. That was something in their internals.

**Pull request merged**
